import { ConjugationExercise } from './types';

export interface CatalogVerb {
  infinitive: string;
  de: string;
  presente: [string, string, string, string, string, string];
  indefinido: [string, string, string, string, string, string];
  futuro: [string, string, string, string, string, string];
  notesPresente?: string;
  notesIndefinido?: string;
}

export const PRONOUNS = ['yo', 'tú', 'él / ella', 'nosotros', 'vosotros', 'ellos / ellas'] as const;

export const VERB_CATALOG: CatalogVerb[] = [
  // ── Ser / Estar / Tener / Haber ─────────────────────────────────────────
  {
    infinitive: 'ser', de: 'sein (dauerhaft)',
    presente:   ['soy', 'eres', 'es', 'somos', 'sois', 'son'],
    indefinido: ['fui', 'fuiste', 'fue', 'fuimos', 'fuisteis', 'fueron'],
    futuro:     ['seré', 'serás', 'será', 'seremos', 'seréis', 'serán'],
    notesPresente: 'ser = permanent state (identity, origin, profession)',
    notesIndefinido: 'Indefinido of ser and ir are identical',
  },
  {
    infinitive: 'estar', de: 'sein (vorübergehend)',
    presente:   ['estoy', 'estás', 'está', 'estamos', 'estáis', 'están'],
    indefinido: ['estuve', 'estuviste', 'estuvo', 'estuvimos', 'estuvisteis', 'estuvieron'],
    futuro:     ['estaré', 'estarás', 'estará', 'estaremos', 'estaréis', 'estarán'],
    notesPresente: 'estar = temporary state (feelings, position, health)',
  },
  {
    infinitive: 'tener', de: 'haben',
    presente:   ['tengo', 'tienes', 'tiene', 'tenemos', 'tenéis', 'tienen'],
    indefinido: ['tuve', 'tuviste', 'tuvo', 'tuvimos', 'tuvisteis', 'tuvieron'],
    futuro:     ['tendré', 'tendrás', 'tendrá', 'tendremos', 'tendréis', 'tendrán'],
    notesPresente: 'Stem e→ie in 2nd/3rd sg. and 3rd pl.',
  },
  {
    infinitive: 'haber', de: 'haben (Hilfsverb)',
    presente:   ['he', 'has', 'ha', 'hemos', 'habéis', 'han'],
    indefinido: ['hube', 'hubiste', 'hubo', 'hubimos', 'hubisteis', 'hubieron'],
    futuro:     ['habré', 'habrás', 'habrá', 'habremos', 'habréis', 'habrán'],
    notesPresente: 'Used to form the perfect: he comido = I have eaten',
  },

  // ── Bewegung & Richtung ─────────────────────────────────────────────────
  {
    infinitive: 'ir', de: 'gehen / fahren',
    presente:   ['voy', 'vas', 'va', 'vamos', 'vais', 'van'],
    indefinido: ['fui', 'fuiste', 'fue', 'fuimos', 'fuisteis', 'fueron'],
    futuro:     ['iré', 'irás', 'irá', 'iremos', 'iréis', 'irán'],
    notesIndefinido: 'Indefinido of ir and ser are identical',
  },
  {
    infinitive: 'venir', de: 'kommen',
    presente:   ['vengo', 'vienes', 'viene', 'venimos', 'venís', 'vienen'],
    indefinido: ['vine', 'viniste', 'vino', 'vinimos', 'vinisteis', 'vinieron'],
    futuro:     ['vendré', 'vendrás', 'vendrá', 'vendremos', 'vendréis', 'vendrán'],
    notesPresente: 'Stem e→ie in 2nd/3rd sg. and 3rd pl.',
  },
  {
    infinitive: 'llegar', de: 'ankommen',
    presente:   ['llego', 'llegas', 'llega', 'llegamos', 'llegáis', 'llegan'],
    indefinido: ['llegué', 'llegaste', 'llegó', 'llegamos', 'llegasteis', 'llegaron'],
    futuro:     ['llegaré', 'llegarás', 'llegará', 'llegaremos', 'llegaréis', 'llegarán'],
    notesIndefinido: 'Spelling: g→gu before e (llegué)',
  },
  {
    infinitive: 'salir', de: 'ausgehen / weggehen',
    presente:   ['salgo', 'sales', 'sale', 'salimos', 'salís', 'salen'],
    indefinido: ['salí', 'saliste', 'salió', 'salimos', 'salisteis', 'salieron'],
    futuro:     ['saldré', 'saldrás', 'saldrá', 'saldremos', 'saldréis', 'saldrán'],
    notesPresente: 'yo: salgo (irregular)',
  },
  {
    infinitive: 'entrar', de: 'eintreten / hereinkommen',
    presente:   ['entro', 'entras', 'entra', 'entramos', 'entráis', 'entran'],
    indefinido: ['entré', 'entraste', 'entró', 'entramos', 'entrasteis', 'entraron'],
    futuro:     ['entraré', 'entrarás', 'entrará', 'entraremos', 'entraréis', 'entrarán'],
  },
  {
    infinitive: 'volver', de: 'zurückkommen / zurückgehen',
    presente:   ['vuelvo', 'vuelves', 'vuelve', 'volvemos', 'volvéis', 'vuelven'],
    indefinido: ['volví', 'volviste', 'volvió', 'volvimos', 'volvisteis', 'volvieron'],
    futuro:     ['volveré', 'volverás', 'volverá', 'volveremos', 'volveréis', 'volverán'],
    notesPresente: 'Stem o→ue in 1st/2nd/3rd sg. and 3rd pl.',
  },
  {
    infinitive: 'caminar', de: 'gehen / spazieren',
    presente:   ['camino', 'caminas', 'camina', 'caminamos', 'camináis', 'caminan'],
    indefinido: ['caminé', 'caminaste', 'caminó', 'caminamos', 'caminasteis', 'caminaron'],
    futuro:     ['caminaré', 'caminarás', 'caminará', 'caminaremos', 'caminaréis', 'caminarán'],
  },
  {
    infinitive: 'correr', de: 'laufen / rennen',
    presente:   ['corro', 'corres', 'corre', 'corremos', 'corréis', 'corren'],
    indefinido: ['corrí', 'corriste', 'corrió', 'corrimos', 'corristeis', 'corrieron'],
    futuro:     ['correré', 'correrás', 'correrá', 'correremos', 'correréis', 'correrán'],
  },
  {
    infinitive: 'subir', de: 'hochgehen / steigen',
    presente:   ['subo', 'subes', 'sube', 'subimos', 'subís', 'suben'],
    indefinido: ['subí', 'subiste', 'subió', 'subimos', 'subisteis', 'subieron'],
    futuro:     ['subiré', 'subirás', 'subirá', 'subiremos', 'subiréis', 'subirán'],
  },
  {
    infinitive: 'bajar', de: 'heruntergehen / sinken',
    presente:   ['bajo', 'bajas', 'baja', 'bajamos', 'bajáis', 'bajan'],
    indefinido: ['bajé', 'bajaste', 'bajó', 'bajamos', 'bajasteis', 'bajaron'],
    futuro:     ['bajaré', 'bajarás', 'bajará', 'bajaremos', 'bajaréis', 'bajarán'],
  },

  // ── Handlungen & Tätigkeiten ─────────────────────────────────────────────
  {
    infinitive: 'hacer', de: 'machen / tun',
    presente:   ['hago', 'haces', 'hace', 'hacemos', 'hacéis', 'hacen'],
    indefinido: ['hice', 'hiciste', 'hizo', 'hicimos', 'hicisteis', 'hicieron'],
    futuro:     ['haré', 'harás', 'hará', 'haremos', 'haréis', 'harán'],
    notesPresente: 'yo: hago (irregular)',
    notesIndefinido: 'hice, but: él hizo (spelling)',
  },
  {
    infinitive: 'dar', de: 'geben',
    presente:   ['doy', 'das', 'da', 'damos', 'dais', 'dan'],
    indefinido: ['di', 'diste', 'dio', 'dimos', 'disteis', 'dieron'],
    futuro:     ['daré', 'darás', 'dará', 'daremos', 'daréis', 'darán'],
    notesPresente: 'yo: doy (irregular)',
    notesIndefinido: 'Like -ir verbs, no accents (monosyllabic)',
  },
  {
    infinitive: 'poner', de: 'stellen / legen / setzen',
    presente:   ['pongo', 'pones', 'pone', 'ponemos', 'ponéis', 'ponen'],
    indefinido: ['puse', 'pusiste', 'puso', 'pusimos', 'pusisteis', 'pusieron'],
    futuro:     ['pondré', 'pondrás', 'pondrá', 'pondremos', 'pondréis', 'pondrán'],
    notesPresente: 'yo: pongo (irregular)',
  },
  {
    infinitive: 'traer', de: 'mitbringen / holen',
    presente:   ['traigo', 'traes', 'trae', 'traemos', 'traéis', 'traen'],
    indefinido: ['traje', 'trajiste', 'trajo', 'trajimos', 'trajisteis', 'trajeron'],
    futuro:     ['traeré', 'traerás', 'traerá', 'traeremos', 'traeréis', 'traerán'],
    notesPresente: 'yo: traigo (irregular)',
    notesIndefinido: 'Stem: traj- (irregular)',
  },
  {
    infinitive: 'llevar', de: 'tragen / mitnehmen',
    presente:   ['llevo', 'llevas', 'lleva', 'llevamos', 'lleváis', 'llevan'],
    indefinido: ['llevé', 'llevaste', 'llevó', 'llevamos', 'llevasteis', 'llevaron'],
    futuro:     ['llevaré', 'llevarás', 'llevará', 'llevaremos', 'llevaréis', 'llevarán'],
  },
  {
    infinitive: 'abrir', de: 'öffnen',
    presente:   ['abro', 'abres', 'abre', 'abrimos', 'abrís', 'abren'],
    indefinido: ['abrí', 'abriste', 'abrió', 'abrimos', 'abristeis', 'abrieron'],
    futuro:     ['abriré', 'abrirás', 'abrirá', 'abriremos', 'abriréis', 'abrirán'],
  },
  {
    infinitive: 'cerrar', de: 'schließen / zumachen',
    presente:   ['cierro', 'cierras', 'cierra', 'cerramos', 'cerráis', 'cierran'],
    indefinido: ['cerré', 'cerraste', 'cerró', 'cerramos', 'cerrasteis', 'cerraron'],
    futuro:     ['cerraré', 'cerrarás', 'cerrará', 'cerraremos', 'cerraréis', 'cerrarán'],
    notesPresente: 'Stem e→ie in 1st/2nd/3rd sg. and 3rd pl.',
  },
  {
    infinitive: 'romper', de: 'brechen / kaputt machen',
    presente:   ['rompo', 'rompes', 'rompe', 'rompemos', 'rompéis', 'rompen'],
    indefinido: ['rompí', 'rompiste', 'rompió', 'rompimos', 'rompisteis', 'rompieron'],
    futuro:     ['romperé', 'romperás', 'romperá', 'romperemos', 'romperéis', 'romperán'],
  },
  {
    infinitive: 'usar', de: 'benutzen / verwenden',
    presente:   ['uso', 'usas', 'usa', 'usamos', 'usáis', 'usan'],
    indefinido: ['usé', 'usaste', 'usó', 'usamos', 'usasteis', 'usaron'],
    futuro:     ['usaré', 'usarás', 'usará', 'usaremos', 'usaréis', 'usarán'],
  },
  {
    infinitive: 'cambiar', de: 'ändern / wechseln',
    presente:   ['cambio', 'cambias', 'cambia', 'cambiamos', 'cambiáis', 'cambian'],
    indefinido: ['cambié', 'cambiaste', 'cambió', 'cambiamos', 'cambiasteis', 'cambiaron'],
    futuro:     ['cambiaré', 'cambiarás', 'cambiará', 'cambiaremos', 'cambiaréis', 'cambiarán'],
  },

  // ── Sprechen & Kommunikation ─────────────────────────────────────────────
  {
    infinitive: 'hablar', de: 'sprechen / reden',
    presente:   ['hablo', 'hablas', 'habla', 'hablamos', 'habláis', 'hablan'],
    indefinido: ['hablé', 'hablaste', 'habló', 'hablamos', 'hablasteis', 'hablaron'],
    futuro:     ['hablaré', 'hablarás', 'hablará', 'hablaremos', 'hablaréis', 'hablarán'],
  },
  {
    infinitive: 'decir', de: 'sagen / erzählen',
    presente:   ['digo', 'dices', 'dice', 'decimos', 'decís', 'dicen'],
    indefinido: ['dije', 'dijiste', 'dijo', 'dijimos', 'dijisteis', 'dijeron'],
    futuro:     ['diré', 'dirás', 'dirá', 'diremos', 'diréis', 'dirán'],
    notesPresente: 'yo: digo; stem e→i',
    notesIndefinido: 'Stem: dij- (irregular)',
  },
  {
    infinitive: 'llamar', de: 'anrufen / rufen',
    presente:   ['llamo', 'llamas', 'llama', 'llamamos', 'llamáis', 'llaman'],
    indefinido: ['llamé', 'llamaste', 'llamó', 'llamamos', 'llamasteis', 'llamaron'],
    futuro:     ['llamaré', 'llamarás', 'llamará', 'llamaremos', 'llamaréis', 'llamarán'],
  },
  {
    infinitive: 'preguntar', de: 'fragen',
    presente:   ['pregunto', 'preguntas', 'pregunta', 'preguntamos', 'preguntáis', 'preguntan'],
    indefinido: ['pregunté', 'preguntaste', 'preguntó', 'preguntamos', 'preguntasteis', 'preguntaron'],
    futuro:     ['preguntaré', 'preguntarás', 'preguntará', 'preguntaremos', 'preguntaréis', 'preguntarán'],
  },
  {
    infinitive: 'contestar', de: 'antworten',
    presente:   ['contesto', 'contestas', 'contesta', 'contestamos', 'contestáis', 'contestan'],
    indefinido: ['contesté', 'contestaste', 'contestó', 'contestamos', 'contestasteis', 'contestaron'],
    futuro:     ['contestaré', 'contestarás', 'contestará', 'contestaremos', 'contestaréis', 'contestarán'],
  },
  {
    infinitive: 'explicar', de: 'erklären',
    presente:   ['explico', 'explicas', 'explica', 'explicamos', 'explicáis', 'explican'],
    indefinido: ['expliqué', 'explicaste', 'explicó', 'explicamos', 'explicasteis', 'explicaron'],
    futuro:     ['explicaré', 'explicarás', 'explicará', 'explicaremos', 'explicaréis', 'explicarán'],
    notesIndefinido: 'Spelling: c→qu before e (expliqué)',
  },
  {
    infinitive: 'escuchar', de: 'zuhören / hören',
    presente:   ['escucho', 'escuchas', 'escucha', 'escuchamos', 'escucháis', 'escuchan'],
    indefinido: ['escuché', 'escuchaste', 'escuchó', 'escuchamos', 'escuchasteis', 'escucharon'],
    futuro:     ['escucharé', 'escucharás', 'escuchará', 'escucharemos', 'escucharéis', 'escucharán'],
  },

  // ── Sehen & Wahrnehmen ───────────────────────────────────────────────────
  {
    infinitive: 'ver', de: 'sehen / schauen',
    presente:   ['veo', 'ves', 've', 'vemos', 'veis', 'ven'],
    indefinido: ['vi', 'viste', 'vio', 'vimos', 'visteis', 'vieron'],
    futuro:     ['veré', 'verás', 'verá', 'veremos', 'veréis', 'verán'],
    notesPresente: 'yo: veo (irregular)',
    notesIndefinido: 'No accents (monosyllabic)',
  },
  {
    infinitive: 'mirar', de: 'ansehen / beobachten',
    presente:   ['miro', 'miras', 'mira', 'miramos', 'miráis', 'miran'],
    indefinido: ['miré', 'miraste', 'miró', 'miramos', 'mirasteis', 'miraron'],
    futuro:     ['miraré', 'mirarás', 'mirará', 'miraremos', 'miraréis', 'mirarán'],
  },
  {
    infinitive: 'buscar', de: 'suchen',
    presente:   ['busco', 'buscas', 'busca', 'buscamos', 'buscáis', 'buscan'],
    indefinido: ['busqué', 'buscaste', 'buscó', 'buscamos', 'buscasteis', 'buscaron'],
    futuro:     ['buscaré', 'buscarás', 'buscará', 'buscaremos', 'buscaréis', 'buscarán'],
    notesIndefinido: 'Spelling: c→qu before e (busqué)',
  },
  {
    infinitive: 'encontrar', de: 'finden / treffen',
    presente:   ['encuentro', 'encuentras', 'encuentra', 'encontramos', 'encontráis', 'encuentran'],
    indefinido: ['encontré', 'encontraste', 'encontró', 'encontramos', 'encontrasteis', 'encontraron'],
    futuro:     ['encontraré', 'encontrarás', 'encontrará', 'encontraremos', 'encontraréis', 'encontrarán'],
    notesPresente: 'Stem o→ue in 1st/2nd/3rd sg. and 3rd pl.',
  },

  // ── Denken & Fühlen ─────────────────────────────────────────────────────
  {
    infinitive: 'poder', de: 'können',
    presente:   ['puedo', 'puedes', 'puede', 'podemos', 'podéis', 'pueden'],
    indefinido: ['pude', 'pudiste', 'pudo', 'pudimos', 'pudisteis', 'pudieron'],
    futuro:     ['podré', 'podrás', 'podrá', 'podremos', 'podréis', 'podrán'],
    notesPresente: 'Stem o→ue in 1st/2nd/3rd sg. and 3rd pl.',
  },
  {
    infinitive: 'querer', de: 'wollen / mögen / lieben',
    presente:   ['quiero', 'quieres', 'quiere', 'queremos', 'queréis', 'quieren'],
    indefinido: ['quise', 'quisiste', 'quiso', 'quisimos', 'quisisteis', 'quisieron'],
    futuro:     ['querré', 'querrás', 'querrá', 'querremos', 'querréis', 'querrán'],
    notesPresente: 'Stem e→ie in 1st/2nd/3rd sg. and 3rd pl.',
  },
  {
    infinitive: 'saber', de: 'wissen / können (gelernt)',
    presente:   ['sé', 'sabes', 'sabe', 'sabemos', 'sabéis', 'saben'],
    indefinido: ['supe', 'supiste', 'supo', 'supimos', 'supisteis', 'supieron'],
    futuro:     ['sabré', 'sabrás', 'sabrá', 'sabremos', 'sabréis', 'sabrán'],
    notesPresente: 'yo: sé (irregular)',
  },
  {
    infinitive: 'conocer', de: 'kennen / kennenlernen',
    presente:   ['conozco', 'conoces', 'conoce', 'conocemos', 'conocéis', 'conocen'],
    indefinido: ['conocí', 'conociste', 'conoció', 'conocimos', 'conocisteis', 'conocieron'],
    futuro:     ['conoceré', 'conocerás', 'conocerá', 'conoceremos', 'conoceréis', 'conocerán'],
    notesPresente: 'yo: conozco (spelling zc)',
  },
  {
    infinitive: 'pensar', de: 'denken / nachdenken',
    presente:   ['pienso', 'piensas', 'piensa', 'pensamos', 'pensáis', 'piensan'],
    indefinido: ['pensé', 'pensaste', 'pensó', 'pensamos', 'pensasteis', 'pensaron'],
    futuro:     ['pensaré', 'pensarás', 'pensará', 'pensaremos', 'pensaréis', 'pensarán'],
    notesPresente: 'Stem e→ie in 1st/2nd/3rd sg. and 3rd pl.',
  },
  {
    infinitive: 'entender', de: 'verstehen',
    presente:   ['entiendo', 'entiendes', 'entiende', 'entendemos', 'entendéis', 'entienden'],
    indefinido: ['entendí', 'entendiste', 'entendió', 'entendimos', 'entendisteis', 'entendieron'],
    futuro:     ['entenderé', 'entenderás', 'entenderá', 'entenderemos', 'entenderéis', 'entenderán'],
    notesPresente: 'Stem e→ie in 1st/2nd/3rd sg. and 3rd pl.',
  },
  {
    infinitive: 'creer', de: 'glauben / denken',
    presente:   ['creo', 'crees', 'cree', 'creemos', 'creéis', 'creen'],
    indefinido: ['creí', 'creíste', 'creyó', 'creímos', 'creísteis', 'creyeron'],
    futuro:     ['creeré', 'creerás', 'creerá', 'creeremos', 'creeréis', 'creerán'],
    notesIndefinido: '3rd person i→y: creyó, creyeron',
  },
  {
    infinitive: 'sentir', de: 'fühlen / empfinden',
    presente:   ['siento', 'sientes', 'siente', 'sentimos', 'sentís', 'sienten'],
    indefinido: ['sentí', 'sentiste', 'sintió', 'sentimos', 'sentisteis', 'sintieron'],
    futuro:     ['sentiré', 'sentirás', 'sentirá', 'sentiremos', 'sentiréis', 'sentirán'],
    notesPresente: 'Stem e→ie in 1st/2nd/3rd sg. and 3rd pl.',
    notesIndefinido: 'Stem e→i in 3rd person',
  },
  {
    infinitive: 'recordar', de: 'sich erinnern',
    presente:   ['recuerdo', 'recuerdas', 'recuerda', 'recordamos', 'recordáis', 'recuerdan'],
    indefinido: ['recordé', 'recordaste', 'recordó', 'recordamos', 'recordasteis', 'recordaron'],
    futuro:     ['recordaré', 'recordarás', 'recordará', 'recordaremos', 'recordaréis', 'recordarán'],
    notesPresente: 'Stem o→ue in 1st/2nd/3rd sg. and 3rd pl.',
  },
  {
    infinitive: 'olvidar', de: 'vergessen',
    presente:   ['olvido', 'olvidas', 'olvida', 'olvidamos', 'olvidáis', 'olvidan'],
    indefinido: ['olvidé', 'olvidaste', 'olvidó', 'olvidamos', 'olvidasteis', 'olvidaron'],
    futuro:     ['olvidaré', 'olvidarás', 'olvidará', 'olvidaremos', 'olvidaréis', 'olvidarán'],
  },
  {
    infinitive: 'esperar', de: 'warten / hoffen',
    presente:   ['espero', 'esperas', 'espera', 'esperamos', 'esperáis', 'esperan'],
    indefinido: ['esperé', 'esperaste', 'esperó', 'esperamos', 'esperasteis', 'esperaron'],
    futuro:     ['esperaré', 'esperarás', 'esperará', 'esperaremos', 'esperaréis', 'esperarán'],
  },
  {
    infinitive: 'preferir', de: 'vorziehen / bevorzugen',
    presente:   ['prefiero', 'prefieres', 'prefiere', 'preferimos', 'preferís', 'prefieren'],
    indefinido: ['preferí', 'preferiste', 'prefirió', 'preferimos', 'preferisteis', 'prefirieron'],
    futuro:     ['preferiré', 'preferirás', 'preferirá', 'preferiremos', 'preferiréis', 'preferirán'],
    notesPresente: 'Stem e→ie in 1st/2nd/3rd sg. and 3rd pl.',
    notesIndefinido: 'Stem e→i in 3rd person',
  },
  {
    infinitive: 'perder', de: 'verlieren',
    presente:   ['pierdo', 'pierdes', 'pierde', 'perdemos', 'perdéis', 'pierden'],
    indefinido: ['perdí', 'perdiste', 'perdió', 'perdimos', 'perdisteis', 'perdieron'],
    futuro:     ['perderé', 'perderás', 'perderá', 'perderemos', 'perderéis', 'perderán'],
    notesPresente: 'Stem e→ie in 1st/2nd/3rd sg. and 3rd pl.',
  },

  // ── Lernen & Arbeiten ────────────────────────────────────────────────────
  {
    infinitive: 'trabajar', de: 'arbeiten',
    presente:   ['trabajo', 'trabajas', 'trabaja', 'trabajamos', 'trabajáis', 'trabajan'],
    indefinido: ['trabajé', 'trabajaste', 'trabajó', 'trabajamos', 'trabajasteis', 'trabajaron'],
    futuro:     ['trabajaré', 'trabajarás', 'trabajará', 'trabajaremos', 'trabajaréis', 'trabajarán'],
  },
  {
    infinitive: 'estudiar', de: 'studieren / lernen',
    presente:   ['estudio', 'estudias', 'estudia', 'estudiamos', 'estudiáis', 'estudian'],
    indefinido: ['estudié', 'estudiaste', 'estudió', 'estudiamos', 'estudiasteis', 'estudiaron'],
    futuro:     ['estudiaré', 'estudiarás', 'estudiará', 'estudiaremos', 'estudiaréis', 'estudiarán'],
  },
  {
    infinitive: 'aprender', de: 'lernen',
    presente:   ['aprendo', 'aprendes', 'aprende', 'aprendemos', 'aprendéis', 'aprenden'],
    indefinido: ['aprendí', 'aprendiste', 'aprendió', 'aprendimos', 'aprendisteis', 'aprendieron'],
    futuro:     ['aprenderé', 'aprenderás', 'aprenderá', 'aprenderemos', 'aprenderéis', 'aprenderán'],
  },
  {
    infinitive: 'enseñar', de: 'unterrichten / zeigen',
    presente:   ['enseño', 'enseñas', 'enseña', 'enseñamos', 'enseñáis', 'enseñan'],
    indefinido: ['enseñé', 'enseñaste', 'enseñó', 'enseñamos', 'enseñasteis', 'enseñaron'],
    futuro:     ['enseñaré', 'enseñarás', 'enseñará', 'enseñaremos', 'enseñaréis', 'enseñarán'],
  },
  {
    infinitive: 'escribir', de: 'schreiben',
    presente:   ['escribo', 'escribes', 'escribe', 'escribimos', 'escribís', 'escriben'],
    indefinido: ['escribí', 'escribiste', 'escribió', 'escribimos', 'escribisteis', 'escribieron'],
    futuro:     ['escribiré', 'escribirás', 'escribirá', 'escribiremos', 'escribiréis', 'escribirán'],
  },
  {
    infinitive: 'leer', de: 'lesen',
    presente:   ['leo', 'lees', 'lee', 'leemos', 'leéis', 'leen'],
    indefinido: ['leí', 'leíste', 'leyó', 'leímos', 'leísteis', 'leyeron'],
    futuro:     ['leeré', 'leerás', 'leerá', 'leeremos', 'leeréis', 'leerán'],
    notesIndefinido: '3rd person i→y: leyó, leyeron',
  },
  {
    infinitive: 'ayudar', de: 'helfen',
    presente:   ['ayudo', 'ayudas', 'ayuda', 'ayudamos', 'ayudáis', 'ayudan'],
    indefinido: ['ayudé', 'ayudaste', 'ayudó', 'ayudamos', 'ayudasteis', 'ayudaron'],
    futuro:     ['ayudaré', 'ayudarás', 'ayudará', 'ayudaremos', 'ayudaréis', 'ayudarán'],
  },
  {
    infinitive: 'necesitar', de: 'brauchen / benötigen',
    presente:   ['necesito', 'necesitas', 'necesita', 'necesitamos', 'necesitáis', 'necesitan'],
    indefinido: ['necesité', 'necesitaste', 'necesitó', 'necesitamos', 'necesitasteis', 'necesitaron'],
    futuro:     ['necesitaré', 'necesitarás', 'necesitará', 'necesitaremos', 'necesitaréis', 'necesitarán'],
  },
  {
    infinitive: 'seguir', de: 'folgen / weitermachen',
    presente:   ['sigo', 'sigues', 'sigue', 'seguimos', 'seguís', 'siguen'],
    indefinido: ['seguí', 'seguiste', 'siguió', 'seguimos', 'seguisteis', 'siguieron'],
    futuro:     ['seguiré', 'seguirás', 'seguirá', 'seguiremos', 'seguiréis', 'seguirán'],
    notesPresente: 'Stem e→i in all forms (yo: sigo)',
    notesIndefinido: 'Stem e→i in 3rd person',
  },
  {
    infinitive: 'empezar', de: 'anfangen / beginnen',
    presente:   ['empiezo', 'empiezas', 'empieza', 'empezamos', 'empezáis', 'empiezan'],
    indefinido: ['empecé', 'empezaste', 'empezó', 'empezamos', 'empezasteis', 'empezaron'],
    futuro:     ['empezaré', 'empezarás', 'empezará', 'empezaremos', 'empezaréis', 'empezarán'],
    notesPresente: 'Stem e→ie in 1st/2nd/3rd sg. and 3rd pl.',
    notesIndefinido: 'Spelling: z→c before e (empecé)',
  },
  {
    infinitive: 'terminar', de: 'beenden / aufhören',
    presente:   ['termino', 'terminas', 'termina', 'terminamos', 'termináis', 'terminan'],
    indefinido: ['terminé', 'terminaste', 'terminó', 'terminamos', 'terminasteis', 'terminaron'],
    futuro:     ['terminaré', 'terminarás', 'terminará', 'terminaremos', 'terminaréis', 'terminarán'],
  },
  {
    infinitive: 'intentar', de: 'versuchen',
    presente:   ['intento', 'intentas', 'intenta', 'intentamos', 'intentáis', 'intentan'],
    indefinido: ['intenté', 'intentaste', 'intentó', 'intentamos', 'intentasteis', 'intentaron'],
    futuro:     ['intentaré', 'intentarás', 'intentará', 'intentaremos', 'intentaréis', 'intentarán'],
  },
  {
    infinitive: 'lograr', de: 'schaffen / erreichen',
    presente:   ['logro', 'logras', 'logra', 'logramos', 'lográis', 'logran'],
    indefinido: ['logré', 'lograste', 'logró', 'logramos', 'lograsteis', 'lograron'],
    futuro:     ['lograré', 'lograrás', 'logrará', 'lograremos', 'lograréis', 'lograrán'],
  },
  {
    infinitive: 'decidir', de: 'entscheiden',
    presente:   ['decido', 'decides', 'decide', 'decidimos', 'decidís', 'deciden'],
    indefinido: ['decidí', 'decidiste', 'decidió', 'decidimos', 'decidisteis', 'decidieron'],
    futuro:     ['decidiré', 'decidirás', 'decidirá', 'decidiremos', 'decidiréis', 'decidirán'],
  },
  {
    infinitive: 'elegir', de: 'wählen / aussuchen',
    presente:   ['elijo', 'eliges', 'elige', 'elegimos', 'elegís', 'eligen'],
    indefinido: ['elegí', 'elegiste', 'eligió', 'elegimos', 'elegisteis', 'eligieron'],
    futuro:     ['elegiré', 'elegirás', 'elegirá', 'elegiremos', 'elegiréis', 'elegirán'],
    notesPresente: 'yo: elijo (spelling g→j before a/o)',
    notesIndefinido: 'Stem e→i in 3rd person',
  },
  {
    infinitive: 'permitir', de: 'erlauben',
    presente:   ['permito', 'permites', 'permite', 'permitimos', 'permitís', 'permiten'],
    indefinido: ['permití', 'permitiste', 'permitió', 'permitimos', 'permitisteis', 'permitieron'],
    futuro:     ['permitiré', 'permitirás', 'permitirá', 'permitiremos', 'permitiréis', 'permitirán'],
  },
  {
    infinitive: 'ofrecer', de: 'anbieten',
    presente:   ['ofrezco', 'ofreces', 'ofrece', 'ofrecemos', 'ofrecéis', 'ofrecen'],
    indefinido: ['ofrecí', 'ofreciste', 'ofreció', 'ofrecimos', 'ofrecisteis', 'ofrecieron'],
    futuro:     ['ofreceré', 'ofrecerás', 'ofrecerá', 'ofreceremos', 'ofreceréis', 'ofrecerán'],
    notesPresente: 'yo: ofrezco (spelling zc)',
  },

  // ── Essen & Trinken ──────────────────────────────────────────────────────
  {
    infinitive: 'comer', de: 'essen',
    presente:   ['como', 'comes', 'come', 'comemos', 'coméis', 'comen'],
    indefinido: ['comí', 'comiste', 'comió', 'comimos', 'comisteis', 'comieron'],
    futuro:     ['comeré', 'comerás', 'comerá', 'comeremos', 'comeréis', 'comerán'],
  },
  {
    infinitive: 'beber', de: 'trinken',
    presente:   ['bebo', 'bebes', 'bebe', 'bebemos', 'bebéis', 'beben'],
    indefinido: ['bebí', 'bebiste', 'bebió', 'bebimos', 'bebisteis', 'bebieron'],
    futuro:     ['beberé', 'beberás', 'beberá', 'beberemos', 'beberéis', 'beberán'],
  },
  {
    infinitive: 'cocinar', de: 'kochen',
    presente:   ['cocino', 'cocinas', 'cocina', 'cocinamos', 'cocináis', 'cocinan'],
    indefinido: ['cociné', 'cocinaste', 'cocinó', 'cocinamos', 'cocinasteis', 'cocinaron'],
    futuro:     ['cocinaré', 'cocinarás', 'cocinará', 'cocinaremos', 'cocinaréis', 'cocinarán'],
  },
  {
    infinitive: 'pedir', de: 'bestellen / bitten',
    presente:   ['pido', 'pides', 'pide', 'pedimos', 'pedís', 'piden'],
    indefinido: ['pedí', 'pediste', 'pidió', 'pedimos', 'pedisteis', 'pidieron'],
    futuro:     ['pediré', 'pedirás', 'pedirá', 'pediremos', 'pediréis', 'pedirán'],
    notesPresente: 'Stem e→i in all forms',
    notesIndefinido: 'Stem e→i in 3rd person',
  },

  // ── Einkaufen & Finanzen ─────────────────────────────────────────────────
  {
    infinitive: 'comprar', de: 'kaufen',
    presente:   ['compro', 'compras', 'compra', 'compramos', 'compráis', 'compran'],
    indefinido: ['compré', 'compraste', 'compró', 'compramos', 'comprasteis', 'compraron'],
    futuro:     ['compraré', 'comprarás', 'comprará', 'compraremos', 'compraréis', 'comprarán'],
  },
  {
    infinitive: 'vender', de: 'verkaufen',
    presente:   ['vendo', 'vendes', 'vende', 'vendemos', 'vendéis', 'venden'],
    indefinido: ['vendí', 'vendiste', 'vendió', 'vendimos', 'vendisteis', 'vendieron'],
    futuro:     ['venderé', 'venderás', 'venderá', 'venderemos', 'venderéis', 'venderán'],
  },
  {
    infinitive: 'pagar', de: 'zahlen / bezahlen',
    presente:   ['pago', 'pagas', 'paga', 'pagamos', 'pagáis', 'pagan'],
    indefinido: ['pagué', 'pagaste', 'pagó', 'pagamos', 'pagasteis', 'pagaron'],
    futuro:     ['pagaré', 'pagarás', 'pagará', 'pagaremos', 'pagaréis', 'pagarán'],
    notesIndefinido: 'Spelling: g→gu before e (pagué)',
  },
  {
    infinitive: 'ganar', de: 'gewinnen / verdienen',
    presente:   ['gano', 'ganas', 'gana', 'ganamos', 'ganáis', 'ganan'],
    indefinido: ['gané', 'ganaste', 'ganó', 'ganamos', 'ganasteis', 'ganaron'],
    futuro:     ['ganaré', 'ganarás', 'ganará', 'ganaremos', 'ganaréis', 'ganarán'],
  },

  // ── Körper & Alltag ──────────────────────────────────────────────────────
  {
    infinitive: 'vivir', de: 'leben / wohnen',
    presente:   ['vivo', 'vives', 'vive', 'vivimos', 'vivís', 'viven'],
    indefinido: ['viví', 'viviste', 'vivió', 'vivimos', 'vivisteis', 'vivieron'],
    futuro:     ['viviré', 'vivirás', 'vivirá', 'viviremos', 'viviréis', 'vivirán'],
  },
  {
    infinitive: 'dormir', de: 'schlafen',
    presente:   ['duermo', 'duermes', 'duerme', 'dormimos', 'dormís', 'duermen'],
    indefinido: ['dormí', 'dormiste', 'durmió', 'dormimos', 'dormisteis', 'durmieron'],
    futuro:     ['dormiré', 'dormirás', 'dormirá', 'dormiremos', 'dormiréis', 'dormirán'],
    notesPresente: 'Stem o→ue in 1st/2nd/3rd sg. and 3rd pl.',
    notesIndefinido: 'Stem o→u in 3rd person',
  },
  {
    infinitive: 'limpiar', de: 'putzen / reinigen',
    presente:   ['limpio', 'limpias', 'limpia', 'limpiamos', 'limpiáis', 'limpian'],
    indefinido: ['limpié', 'limpiaste', 'limpió', 'limpiamos', 'limpiasteis', 'limpiaron'],
    futuro:     ['limpiaré', 'limpiarás', 'limpiará', 'limpiaremos', 'limpiaréis', 'limpiarán'],
  },
  {
    infinitive: 'nadar', de: 'schwimmen',
    presente:   ['nado', 'nadas', 'nada', 'nadamos', 'nadáis', 'nadan'],
    indefinido: ['nadé', 'nadaste', 'nadó', 'nadamos', 'nadasteis', 'nadaron'],
    futuro:     ['nadaré', 'nadarás', 'nadará', 'nadaremos', 'nadaréis', 'nadarán'],
  },
  {
    infinitive: 'cantar', de: 'singen',
    presente:   ['canto', 'cantas', 'canta', 'cantamos', 'cantáis', 'cantan'],
    indefinido: ['canté', 'cantaste', 'cantó', 'cantamos', 'cantasteis', 'cantaron'],
    futuro:     ['cantaré', 'cantarás', 'cantará', 'cantaremos', 'cantaréis', 'cantarán'],
  },
  {
    infinitive: 'bailar', de: 'tanzen',
    presente:   ['bailo', 'bailas', 'baila', 'bailamos', 'bailáis', 'bailan'],
    indefinido: ['bailé', 'bailaste', 'bailó', 'bailamos', 'bailasteis', 'bailaron'],
    futuro:     ['bailaré', 'bailarás', 'bailará', 'bailaremos', 'bailaréis', 'bailarán'],
  },
  {
    infinitive: 'jugar', de: 'spielen',
    presente:   ['juego', 'juegas', 'juega', 'jugamos', 'jugáis', 'juegan'],
    indefinido: ['jugué', 'jugaste', 'jugó', 'jugamos', 'jugasteis', 'jugaron'],
    futuro:     ['jugaré', 'jugarás', 'jugará', 'jugaremos', 'jugaréis', 'jugarán'],
    notesPresente: 'Stem u→ue in 1st/2nd/3rd sg. and 3rd pl.',
    notesIndefinido: 'Spelling: g→gu before e (jugué)',
  },
  {
    infinitive: 'saltar', de: 'springen',
    presente:   ['salto', 'saltas', 'salta', 'saltamos', 'saltáis', 'saltan'],
    indefinido: ['salté', 'saltaste', 'saltó', 'saltamos', 'saltasteis', 'saltaron'],
    futuro:     ['saltaré', 'saltarás', 'saltará', 'saltaremos', 'saltaréis', 'saltarán'],
  },

  // ── Gefühle & Beziehungen ────────────────────────────────────────────────
  {
    infinitive: 'amar', de: 'lieben',
    presente:   ['amo', 'amas', 'ama', 'amamos', 'amáis', 'aman'],
    indefinido: ['amé', 'amaste', 'amó', 'amamos', 'amasteis', 'amaron'],
    futuro:     ['amaré', 'amarás', 'amará', 'amaremos', 'amaréis', 'amarán'],
  },
  {
    infinitive: 'odiar', de: 'hassen',
    presente:   ['odio', 'odias', 'odia', 'odiamos', 'odiáis', 'odian'],
    indefinido: ['odié', 'odiaste', 'odió', 'odiamos', 'odiasteis', 'odiaron'],
    futuro:     ['odiaré', 'odiarás', 'odiará', 'odiaremos', 'odiaréis', 'odiarán'],
  },
  {
    infinitive: 'prometer', de: 'versprechen',
    presente:   ['prometo', 'prometes', 'promete', 'prometemos', 'prometéis', 'prometen'],
    indefinido: ['prometí', 'prometiste', 'prometió', 'prometimos', 'prometisteis', 'prometieron'],
    futuro:     ['prometeré', 'prometerás', 'prometerá', 'prometeremos', 'prometeréis', 'prometerán'],
  },
  {
    infinitive: 'confiar', de: 'vertrauen',
    presente:   ['confío', 'confías', 'confía', 'confiamos', 'confiáis', 'confían'],
    indefinido: ['confié', 'confiaste', 'confió', 'confiamos', 'confiasteis', 'confiaron'],
    futuro:     ['confiaré', 'confiarás', 'confiará', 'confiaremos', 'confiaréis', 'confiarán'],
    notesPresente: 'Accent on í in sg. and 3rd pl.',
  },
  {
    infinitive: 'mentir', de: 'lügen',
    presente:   ['miento', 'mientes', 'miente', 'mentimos', 'mentís', 'mienten'],
    indefinido: ['mentí', 'mentiste', 'mintió', 'mentimos', 'mentisteis', 'mintieron'],
    futuro:     ['mentiré', 'mentirás', 'mentirá', 'mentiremos', 'mentiréis', 'mentirán'],
    notesPresente: 'Stem e→ie in 1st/2nd/3rd sg. and 3rd pl.',
    notesIndefinido: 'Stem e→i in 3rd person',
  },
  {
    infinitive: 'sufrir', de: 'leiden',
    presente:   ['sufro', 'sufres', 'sufre', 'sufrimos', 'sufrís', 'sufren'],
    indefinido: ['sufrí', 'sufriste', 'sufrió', 'sufrimos', 'sufristeis', 'sufrieron'],
    futuro:     ['sufriré', 'sufrirás', 'sufrirá', 'sufriremos', 'sufriréis', 'sufrirán'],
  },
  {
    infinitive: 'disfrutar', de: 'genießen',
    presente:   ['disfruto', 'disfrutas', 'disfruta', 'disfrutamos', 'disfrutáis', 'disfrutan'],
    indefinido: ['disfruté', 'disfrutaste', 'disfrutó', 'disfrutamos', 'disfrutasteis', 'disfrutaron'],
    futuro:     ['disfrutaré', 'disfrutarás', 'disfrutará', 'disfrutaremos', 'disfrutaréis', 'disfrutarán'],
  },
  {
    infinitive: 'divertirse', de: 'Spaß haben / sich amüsieren',
    presente:   ['me divierto', 'te diviertes', 'se divierte', 'nos divertimos', 'os divertís', 'se divierten'],
    indefinido: ['me divertí', 'te divertiste', 'se divirtió', 'nos divertimos', 'os divertisteis', 'se divirtieron'],
    futuro:     ['me divertiré', 'te divertirás', 'se divertirá', 'nos divertiremos', 'os divertiréis', 'se divertirán'],
    notesPresente: 'Reflexivverb; Stem e→ie in 1st/2nd/3rd sg. and 3rd pl.',
  },
  {
    infinitive: 'preocuparse', de: 'sich sorgen / sich aufregen',
    presente:   ['me preocupo', 'te preocupas', 'se preocupa', 'nos preocupamos', 'os preocupáis', 'se preocupan'],
    indefinido: ['me preocupé', 'te preocupaste', 'se preocupó', 'nos preocupamos', 'os preocupasteis', 'se preocuparon'],
    futuro:     ['me preocuparé', 'te preocuparás', 'se preocupará', 'nos preocuparemos', 'os preocuparéis', 'se preocuparán'],
    notesPresente: 'Reflexivverb',
  },

  // ── Natur & Entstehung ───────────────────────────────────────────────────
  {
    infinitive: 'nacer', de: 'geboren werden',
    presente:   ['nazco', 'naces', 'nace', 'nacemos', 'nacéis', 'nacen'],
    indefinido: ['nací', 'naciste', 'nació', 'nacimos', 'nacisteis', 'nacieron'],
    futuro:     ['naceré', 'nacerás', 'nacerá', 'naceremos', 'naceréis', 'nacerán'],
    notesPresente: 'yo: nazco (spelling zc)',
  },
  {
    infinitive: 'morir', de: 'sterben',
    presente:   ['muero', 'mueres', 'muere', 'morimos', 'morís', 'mueren'],
    indefinido: ['morí', 'moriste', 'murió', 'morimos', 'moristeis', 'murieron'],
    futuro:     ['moriré', 'morirás', 'morirá', 'moriremos', 'moriréis', 'morirán'],
    notesPresente: 'Stem o→ue in 1st/2nd/3rd sg. and 3rd pl.',
    notesIndefinido: 'Stem o→u in 3rd person',
  },
  {
    infinitive: 'crecer', de: 'wachsen',
    presente:   ['crezco', 'creces', 'crece', 'crecemos', 'crecéis', 'crecen'],
    indefinido: ['crecí', 'creciste', 'creció', 'crecimos', 'crecisteis', 'crecieron'],
    futuro:     ['creceré', 'crecerás', 'crecerá', 'creceremos', 'creceréis', 'crecerán'],
    notesPresente: 'yo: crezco (spelling zc)',
  },
  {
    infinitive: 'aparecer', de: 'erscheinen / auftauchen',
    presente:   ['aparezco', 'apareces', 'aparece', 'aparecemos', 'aparecéis', 'aparecen'],
    indefinido: ['aparecí', 'apareciste', 'apareció', 'aparecimos', 'aparecisteis', 'aparecieron'],
    futuro:     ['apareceré', 'aparecerás', 'aparecerá', 'apareceremos', 'apareceréis', 'aparecerán'],
    notesPresente: 'yo: aparezco (spelling zc)',
  },

  // ── Konstruieren & Erschaffen ────────────────────────────────────────────
  {
    infinitive: 'construir', de: 'bauen / aufbauen',
    presente:   ['construyo', 'construyes', 'construye', 'construimos', 'construís', 'construyen'],
    indefinido: ['construí', 'construiste', 'construyó', 'construimos', 'construisteis', 'construyeron'],
    futuro:     ['construiré', 'construirás', 'construirá', 'construiremos', 'construiréis', 'construirán'],
    notesPresente: 'i→y vor Vokal: construyo, construyes...',
    notesIndefinido: 'i→y in 3rd person: construyó, construyeron',
  },
  {
    infinitive: 'destruir', de: 'zerstören',
    presente:   ['destruyo', 'destruyes', 'destruye', 'destruimos', 'destruís', 'destruyen'],
    indefinido: ['destruí', 'destruiste', 'destruyó', 'destruimos', 'destruisteis', 'destruyeron'],
    futuro:     ['destruiré', 'destruirás', 'destruirá', 'destruiremos', 'destruiréis', 'destruirán'],
    notesPresente: 'i→y vor Vokal (wie construir)',
    notesIndefinido: 'i→y in 3rd person',
  },
  {
    infinitive: 'crear', de: 'erschaffen / erstellen',
    presente:   ['creo', 'creas', 'crea', 'creamos', 'creáis', 'crean'],
    indefinido: ['creé', 'creaste', 'creó', 'creamos', 'creasteis', 'crearon'],
    futuro:     ['crearé', 'crearás', 'creará', 'crearemos', 'crearéis', 'crearán'],
  },
  {
    infinitive: 'mostrar', de: 'zeigen / vorführen',
    presente:   ['muestro', 'muestras', 'muestra', 'mostramos', 'mostráis', 'muestran'],
    indefinido: ['mostré', 'mostraste', 'mostró', 'mostramos', 'mostrasteis', 'mostraron'],
    futuro:     ['mostraré', 'mostrarás', 'mostrará', 'mostraremos', 'mostraréis', 'mostrarán'],
    notesPresente: 'Stem o→ue in 1st/2nd/3rd sg. and 3rd pl.',
  },
  {
    infinitive: 'descubrir', de: 'entdecken',
    presente:   ['descubro', 'descubres', 'descubre', 'descubrimos', 'descubrís', 'descubren'],
    indefinido: ['descubrí', 'descubriste', 'descubrió', 'descubrimos', 'descubristeis', 'descubrieron'],
    futuro:     ['descubriré', 'descubrirás', 'descubrirá', 'descubriremos', 'descubriréis', 'descubrirán'],
  },
  {
    infinitive: 'resolver', de: 'lösen / klären',
    presente:   ['resuelvo', 'resuelves', 'resuelve', 'resolvemos', 'resolvéis', 'resuelven'],
    indefinido: ['resolví', 'resolviste', 'resolvió', 'resolvimos', 'resolvisteis', 'resolvieron'],
    futuro:     ['resolveré', 'resolverás', 'resolverá', 'resolveremos', 'resolveréis', 'resolverán'],
    notesPresente: 'Stem o→ue in 1st/2nd/3rd sg. and 3rd pl.',
  },
  {
    infinitive: 'mejorar', de: 'verbessern',
    presente:   ['mejoro', 'mejoras', 'mejora', 'mejoramos', 'mejoráis', 'mejoran'],
    indefinido: ['mejoré', 'mejoraste', 'mejoró', 'mejoramos', 'mejorasteis', 'mejoraron'],
    futuro:     ['mejoraré', 'mejorarás', 'mejorará', 'mejoraremos', 'mejoraréis', 'mejorarán'],
  },
  {
    infinitive: 'merecer', de: 'verdienen / es wert sein',
    presente:   ['merezco', 'mereces', 'merece', 'merecemos', 'merecéis', 'merecen'],
    indefinido: ['merecí', 'mereciste', 'mereció', 'merecimos', 'merecisteis', 'merecieron'],
    futuro:     ['mereceré', 'merecerás', 'merecerá', 'mereceremos', 'mereceréis', 'merecerán'],
    notesPresente: 'yo: merezco (spelling zc)',
  },

  // ── Weitere wichtige unregelmäßige Verben ────────────────────────────────
  {
    infinitive: 'oír', de: 'hören (wahrnehmen)',
    presente:   ['oigo', 'oyes', 'oye', 'oímos', 'oís', 'oyen'],
    indefinido: ['oí', 'oíste', 'oyó', 'oímos', 'oísteis', 'oyeron'],
    futuro:     ['oiré', 'oirás', 'oirá', 'oiremos', 'oiréis', 'oirán'],
    notesPresente: 'yo: oigo; i→y vor Vokal: oyes, oye, oyen',
    notesIndefinido: 'i→y in 3rd person: oyó, oyeron',
  },
  {
    infinitive: 'caer', de: 'fallen',
    presente:   ['caigo', 'caes', 'cae', 'caemos', 'caéis', 'caen'],
    indefinido: ['caí', 'caíste', 'cayó', 'caímos', 'caísteis', 'cayeron'],
    futuro:     ['caeré', 'caerás', 'caerá', 'caeremos', 'caeréis', 'caerán'],
    notesPresente: 'yo: caigo (irregular)',
    notesIndefinido: 'i→y in 3rd person: cayó, cayeron',
  },
  {
    infinitive: 'conducir', de: 'fahren / leiten',
    presente:   ['conduzco', 'conduces', 'conduce', 'conducimos', 'conducís', 'conducen'],
    indefinido: ['conduje', 'condujiste', 'condujo', 'condujimos', 'condujisteis', 'condujeron'],
    futuro:     ['conduciré', 'conducirás', 'conducirá', 'conduciremos', 'conduciréis', 'conducirán'],
    notesPresente: 'yo: conduzco (spelling zc)',
    notesIndefinido: 'Stem: conduj- (irregular)',
  },
  {
    infinitive: 'traducir', de: 'übersetzen',
    presente:   ['traduzco', 'traduces', 'traduce', 'traducimos', 'traducís', 'traducen'],
    indefinido: ['traduje', 'tradujiste', 'tradujo', 'tradujimos', 'tradujisteis', 'tradujeron'],
    futuro:     ['traduciré', 'traducirás', 'traducirá', 'traduciremos', 'traduciréis', 'traducirán'],
    notesPresente: 'yo: traduzco (spelling zc)',
    notesIndefinido: 'Stem: traduj- (like conducir)',
  },
  {
    infinitive: 'producir', de: 'produzieren / herstellen',
    presente:   ['produzco', 'produces', 'produce', 'producimos', 'producís', 'producen'],
    indefinido: ['produje', 'produjiste', 'produjo', 'produjimos', 'produjisteis', 'produjeron'],
    futuro:     ['produciré', 'producirás', 'producirá', 'produciremos', 'produciréis', 'producirán'],
    notesPresente: 'yo: produzco (spelling zc)',
    notesIndefinido: 'Stem: produj- (like conducir)',
  },
  {
    infinitive: 'obtener', de: 'erhalten / bekommen',
    presente:   ['obtengo', 'obtienes', 'obtiene', 'obtenemos', 'obtenéis', 'obtienen'],
    indefinido: ['obtuve', 'obtuviste', 'obtuvo', 'obtuvimos', 'obtuvisteis', 'obtuvieron'],
    futuro:     ['obtendré', 'obtendrás', 'obtendrá', 'obtendremos', 'obtendréis', 'obtendrán'],
    notesPresente: 'Wie tener (yo: obtengo, e→ie)',
    notesIndefinido: 'Wie tener (Stamm: obtuv-)',
  },
  {
    infinitive: 'mantener', de: 'aufrechterhalten / beibehalten',
    presente:   ['mantengo', 'mantienes', 'mantiene', 'mantenemos', 'mantenéis', 'mantienen'],
    indefinido: ['mantuve', 'mantuviste', 'mantuvo', 'mantuvimos', 'mantuvisteis', 'mantuvieron'],
    futuro:     ['mantendré', 'mantendrás', 'mantendrá', 'mantendremos', 'mantendréis', 'mantendrán'],
    notesPresente: 'Wie tener (yo: mantengo, e→ie)',
    notesIndefinido: 'Wie tener (Stamm: mantuv-)',
  },
  {
    infinitive: 'contener', de: 'enthalten / zurückhalten',
    presente:   ['contengo', 'contienes', 'contiene', 'contenemos', 'contenéis', 'contienen'],
    indefinido: ['contuve', 'contuviste', 'contuvo', 'contuvimos', 'contuvisteis', 'contuvieron'],
    futuro:     ['contendré', 'contendrás', 'contendrá', 'contendremos', 'contendréis', 'contendrán'],
    notesPresente: 'Wie tener (yo: contengo, e→ie)',
  },
  {
    infinitive: 'valer', de: 'wert sein / kosten',
    presente:   ['valgo', 'vales', 'vale', 'valemos', 'valéis', 'valen'],
    indefinido: ['valí', 'valiste', 'valió', 'valimos', 'valisteis', 'valieron'],
    futuro:     ['valdré', 'valdrás', 'valdrá', 'valdremos', 'valdréis', 'valdrán'],
    notesPresente: 'yo: valgo (irregular)',
  },
  {
    infinitive: 'caber', de: 'hineinpassen / Platz haben',
    presente:   ['quepo', 'cabes', 'cabe', 'cabemos', 'cabéis', 'caben'],
    indefinido: ['cupe', 'cupiste', 'cupo', 'cupimos', 'cupisteis', 'cupieron'],
    futuro:     ['cabré', 'cabrás', 'cabrá', 'cabremos', 'cabréis', 'cabrán'],
    notesPresente: 'yo: quepo (sehr irregular)',
  },
  {
    infinitive: 'suponer', de: 'annehmen / vermuten',
    presente:   ['supongo', 'supones', 'supone', 'suponemos', 'suponéis', 'suponen'],
    indefinido: ['supuse', 'supusiste', 'supuso', 'supusimos', 'supusisteis', 'supusieron'],
    futuro:     ['supondré', 'supondrás', 'supondrá', 'supondremos', 'supondréis', 'supondrán'],
    notesPresente: 'Wie poner (yo: supongo)',
    notesIndefinido: 'Wie poner (Stamm: supus-)',
  },
  {
    infinitive: 'proponer', de: 'vorschlagen',
    presente:   ['propongo', 'propones', 'propone', 'proponemos', 'proponéis', 'proponen'],
    indefinido: ['propuse', 'propusiste', 'propuso', 'propusimos', 'propusisteis', 'propusieron'],
    futuro:     ['propondré', 'propondrás', 'propondrá', 'propondremos', 'propondréis', 'propondrán'],
    notesPresente: 'Wie poner (yo: propongo)',
  },
  {
    infinitive: 'componer', de: 'komponieren / zusammensetzen',
    presente:   ['compongo', 'compones', 'compone', 'componemos', 'componéis', 'componen'],
    indefinido: ['compuse', 'compusiste', 'compuso', 'compusimos', 'compusisteis', 'compusieron'],
    futuro:     ['compondré', 'compondrás', 'compondrá', 'compondremos', 'compondréis', 'compondrán'],
    notesPresente: 'Wie poner (yo: compongo)',
  },
  {
    infinitive: 'convenir', de: 'passen / übereinkommen',
    presente:   ['convengo', 'convienes', 'conviene', 'convenimos', 'convenís', 'convienen'],
    indefinido: ['convine', 'conviniste', 'convino', 'convinimos', 'convinisteis', 'convinieron'],
    futuro:     ['convendré', 'convendrás', 'convendrá', 'convendremos', 'convendréis', 'convendrán'],
    notesPresente: 'Wie venir (yo: convengo)',
  },
  {
    infinitive: 'detener', de: 'anhalten / aufhalten',
    presente:   ['detengo', 'detienes', 'detiene', 'detenemos', 'detenéis', 'detienen'],
    indefinido: ['detuve', 'detuviste', 'detuvo', 'detuvimos', 'detuvisteis', 'detuvieron'],
    futuro:     ['detendré', 'detendrás', 'detendrá', 'detendremos', 'detendréis', 'detendrán'],
    notesPresente: 'Wie tener (yo: detengo)',
  },
  {
    infinitive: 'devolver', de: 'zurückgeben / zurückbringen',
    presente:   ['devuelvo', 'devuelves', 'devuelve', 'devolvemos', 'devolvéis', 'devuelven'],
    indefinido: ['devolví', 'devolviste', 'devolvió', 'devolvimos', 'devolvisteis', 'devolvieron'],
    futuro:     ['devolveré', 'devolverás', 'devolverá', 'devolveremos', 'devolveréis', 'devolverán'],
    notesPresente: 'Wie volver (o→ue)',
  },
  {
    infinitive: 'envolver', de: 'einwickeln / umhüllen',
    presente:   ['envuelvo', 'envuelves', 'envuelve', 'envolvemos', 'envolvéis', 'envuelven'],
    indefinido: ['envolví', 'envolviste', 'envolvió', 'envolvimos', 'envolvisteis', 'envolvieron'],
    futuro:     ['envolveré', 'envolverás', 'envolverá', 'envolveremos', 'envolveréis', 'envolverán'],
    notesPresente: 'Wie volver (o→ue)',
  },
  {
    infinitive: 'repetir', de: 'wiederholen',
    presente:   ['repito', 'repites', 'repite', 'repetimos', 'repetís', 'repiten'],
    indefinido: ['repetí', 'repetiste', 'repitió', 'repetimos', 'repetisteis', 'repitieron'],
    futuro:     ['repetiré', 'repetirás', 'repetirá', 'repetiremos', 'repetiréis', 'repetirán'],
    notesPresente: 'Stem e→i in all forms',
    notesIndefinido: 'Stem e→i in 3rd person',
  },
  {
    infinitive: 'competir', de: 'konkurrieren / wettkämpfen',
    presente:   ['compito', 'compites', 'compite', 'competimos', 'competís', 'compiten'],
    indefinido: ['competí', 'competiste', 'compitió', 'competimos', 'competisteis', 'compitieron'],
    futuro:     ['competiré', 'competirás', 'competirá', 'competiremos', 'competiréis', 'competirán'],
    notesPresente: 'Wie pedir (e→i)',
    notesIndefinido: 'Stem e→i in 3rd person',
  },
  {
    infinitive: 'despedir', de: 'verabschieden / entlassen',
    presente:   ['despido', 'despides', 'despide', 'despedimos', 'despedís', 'despiden'],
    indefinido: ['despedí', 'despediste', 'despidió', 'despedimos', 'despedisteis', 'despidieron'],
    futuro:     ['despediré', 'despedirás', 'despedirá', 'despediremos', 'despediréis', 'despedirán'],
    notesPresente: 'Wie pedir (e→i)',
    notesIndefinido: 'Stem e→i in 3rd person',
  },
  {
    infinitive: 'huir', de: 'fliehen / flüchten',
    presente:   ['huyo', 'huyes', 'huye', 'huimos', 'huís', 'huyen'],
    indefinido: ['huí', 'huiste', 'huyó', 'huimos', 'huisteis', 'huyeron'],
    futuro:     ['huiré', 'huirás', 'huirá', 'huiremos', 'huiréis', 'huirán'],
    notesPresente: 'i→y vor Vokal (wie construir)',
    notesIndefinido: 'i→y in 3rd person: huyó, huyeron',
  },
  {
    infinitive: 'incluir', de: 'einschließen / beinhalten',
    presente:   ['incluyo', 'incluyes', 'incluye', 'incluimos', 'incluís', 'incluyen'],
    indefinido: ['incluí', 'incluiste', 'incluyó', 'incluimos', 'incluisteis', 'incluyeron'],
    futuro:     ['incluiré', 'incluirás', 'incluirá', 'incluiremos', 'incluiréis', 'incluirán'],
    notesPresente: 'i→y vor Vokal (wie construir)',
    notesIndefinido: 'i→y in 3rd person',
  },
  {
    infinitive: 'excluir', de: 'ausschließen',
    presente:   ['excluyo', 'excluyes', 'excluye', 'excluimos', 'excluís', 'excluyen'],
    indefinido: ['excluí', 'excluiste', 'excluyó', 'excluimos', 'excluisteis', 'excluyeron'],
    futuro:     ['excluiré', 'excluirás', 'excluirá', 'excluiremos', 'excluiréis', 'excluirán'],
    notesPresente: 'i→y vor Vokal (wie construir)',
  },
  {
    infinitive: 'reír', de: 'lachen',
    presente:   ['río', 'ríes', 'ríe', 'reímos', 'reís', 'ríen'],
    indefinido: ['reí', 'reíste', 'rió', 'reímos', 'reísteis', 'rieron'],
    futuro:     ['reiré', 'reirás', 'reirá', 'reiremos', 'reiréis', 'reirán'],
    notesPresente: 'Stamm e→i mit Akzent (río, ríes, ríe, ríen)',
  },
  {
    infinitive: 'sonreír', de: 'lächeln',
    presente:   ['sonrío', 'sonríes', 'sonríe', 'sonreímos', 'sonreís', 'sonríen'],
    indefinido: ['sonreí', 'sonreíste', 'sonrió', 'sonreímos', 'sonreísteis', 'sonrieron'],
    futuro:     ['sonreiré', 'sonreirás', 'sonreirá', 'sonreiremos', 'sonreiréis', 'sonreirán'],
    notesPresente: 'Wie reír (e→i mit Akzent)',
  },
  {
    infinitive: 'coger', de: 'nehmen / greifen',
    presente:   ['cojo', 'coges', 'coge', 'cogemos', 'cogéis', 'cogen'],
    indefinido: ['cogí', 'cogiste', 'cogió', 'cogimos', 'cogisteis', 'cogieron'],
    futuro:     ['cogeré', 'cogerás', 'cogerá', 'cogeremos', 'cogeréis', 'cogerán'],
    notesPresente: 'yo: cojo (Schreibung g→j vor a/o)',
  },
  {
    infinitive: 'exigir', de: 'verlangen / fordern',
    presente:   ['exijo', 'exiges', 'exige', 'exigimos', 'exigís', 'exigen'],
    indefinido: ['exigí', 'exigiste', 'exigió', 'exigimos', 'exigisteis', 'exigieron'],
    futuro:     ['exigiré', 'exigirás', 'exigirá', 'exigiremos', 'exigiréis', 'exigirán'],
    notesPresente: 'yo: exijo (Schreibung g→j vor a/o)',
  },
  {
    infinitive: 'proteger', de: 'schützen',
    presente:   ['protejo', 'proteges', 'protege', 'protegemos', 'protegéis', 'protegen'],
    indefinido: ['protegí', 'protegiste', 'protegió', 'protegimos', 'protegisteis', 'protegieron'],
    futuro:     ['protegeré', 'protegerás', 'protegerá', 'protegeremos', 'protegeréis', 'protegerán'],
    notesPresente: 'yo: protejo (Schreibung g→j vor a/o)',
  },
  {
    infinitive: 'vencer', de: 'besiegen / überwinden',
    presente:   ['venzo', 'vences', 'vence', 'vencemos', 'vencéis', 'vencen'],
    indefinido: ['vencí', 'venciste', 'venció', 'vencimos', 'vencisteis', 'vencieron'],
    futuro:     ['venceré', 'vencerás', 'vencerá', 'venceremos', 'venceréis', 'vencerán'],
    notesPresente: 'yo: venzo (Schreibung c→z vor a/o)',
  },
  {
    infinitive: 'torcer', de: 'drehen / verdrehen',
    presente:   ['tuerzo', 'tuerces', 'tuerce', 'torcemos', 'torcéis', 'tuercen'],
    indefinido: ['torcí', 'torciste', 'torció', 'torcimos', 'torcisteis', 'torcieron'],
    futuro:     ['torceré', 'torcerás', 'torcerá', 'torceremos', 'torceréis', 'torcerán'],
    notesPresente: 'o→ue + Schreibung c→z vor a/o: tuerzo',
  },
  {
    infinitive: 'mover', de: 'bewegen',
    presente:   ['muevo', 'mueves', 'mueve', 'movemos', 'movéis', 'mueven'],
    indefinido: ['moví', 'moviste', 'movió', 'movimos', 'movisteis', 'movieron'],
    futuro:     ['moveré', 'moverás', 'moverá', 'moveremos', 'moveréis', 'moverán'],
    notesPresente: 'Stem o→ue in 1st/2nd/3rd sg. and 3rd pl.',
  },
];

export function verbToExercise(verb: CatalogVerb): ConjugationExercise {
  return {
    type: 'conjugation',
    title: `${verb.infinitive} – Conjugation`,
    verb: verb.infinitive,
    instruction: `Conjugate "${verb.infinitive}" (${verb.de}) in the present, preterite and future.`,
    sections: [
      {
        tense: 'presente',
        tenseName_de: 'Present (Präsens)',
        pronouns: [...PRONOUNS],
        answers: [...verb.presente],
        notes: verb.notesPresente,
      },
      {
        tense: 'preterito_indefinido',
        tenseName_de: 'Preterite (Indefinido)',
        pronouns: [...PRONOUNS],
        answers: [...verb.indefinido],
        notes: verb.notesIndefinido,
      },
      {
        tense: 'futuro_simple',
        tenseName_de: 'Future (Futuro)',
        pronouns: [...PRONOUNS],
        answers: [...verb.futuro],
      },
    ],
  };
}

export function pickNextVerb(knownVerbs: string[]): CatalogVerb {
  const known = new Set(knownVerbs.map(v => v.toLowerCase()));
  const unseen = VERB_CATALOG.filter(v => !known.has(v.infinitive.toLowerCase()));
  const pool = unseen.length > 0 ? unseen : VERB_CATALOG;
  return pool[Math.floor(Math.random() * Math.min(pool.length, 5))];
}

export function findVerb(infinitive: string): CatalogVerb | null {
  return VERB_CATALOG.find(v => v.infinitive.toLowerCase() === infinitive.toLowerCase()) ?? null;
}
