import { CatalogWord } from './vocab-catalog';

// ─── A1 → A2 starter path ───────────────────────────────────────────────────────
// A gentle, ordered on-ramp for complete beginners (Emmi). The Vocabulary "Learn"
// tab walks this array in order, so the ORDER here is the teaching order: start with
// greetings, courtesy, question words, pronouns and numbers — the things the main
// VOCAB_CATALOG lacks and that a true beginner needs first — then move through the
// most concrete everyday themes (family, food, house, city, travel…) before the
// lighter abstract words. German (`de`) side is the learner's L1.
//
// 700+ words, deduped at the bottom so an accidental repeat never produces a double
// flashcard. After the starter, app/vokabeln/page.tsx flows beginners into the rest
// of the full catalog, so they never run out.

const RAW: CatalogWord[] = [
  // ── Begrüßung & Höflichkeit ────────────────────────────────────────────────
  { de: 'hallo', es: 'hola' },
  { de: 'guten Morgen', es: 'buenos días' },
  { de: 'guten Tag / guten Nachmittag', es: 'buenas tardes' },
  { de: 'gute Nacht', es: 'buenas noches' },
  { de: 'tschüss', es: 'adiós' },
  { de: 'bis später', es: 'hasta luego' },
  { de: 'bis morgen', es: 'hasta mañana' },
  { de: 'willkommen', es: 'bienvenido' },
  { de: 'ja', es: 'sí' },
  { de: 'nein', es: 'no' },
  { de: 'vielleicht', es: 'quizás' },
  { de: 'bitte', es: 'por favor' },
  { de: 'danke', es: 'gracias' },
  { de: 'vielen Dank', es: 'muchas gracias' },
  { de: 'gern geschehen', es: 'de nada' },
  { de: 'entschuldigung', es: 'perdón' },
  { de: 'es tut mir leid', es: 'lo siento' },
  { de: 'Verzeihung (Aufmerksamkeit)', es: 'disculpe' },
  { de: 'wie geht es dir?', es: '¿cómo estás?' },
  { de: 'gut', es: 'bien' },
  { de: 'schlecht', es: 'mal' },
  { de: 'so lala', es: 'más o menos' },
  { de: 'sehr erfreut', es: 'mucho gusto' },
  { de: 'wie heißt du?', es: '¿cómo te llamas?' },
  { de: 'ich heiße …', es: 'me llamo' },
  { de: 'ich verstehe nicht', es: 'no entiendo' },
  { de: 'sprichst du Deutsch?', es: '¿hablas alemán?' },
  { de: 'Prost!', es: '¡salud!' },
  { de: 'herzlichen Glückwunsch', es: 'felicidades' },

  // ── Fragewörter ─────────────────────────────────────────────────────────────
  { de: 'was', es: 'qué' },
  { de: 'wer', es: 'quién' },
  { de: 'wo', es: 'dónde' },
  { de: 'wohin', es: 'adónde' },
  { de: 'wann', es: 'cuándo' },
  { de: 'wie', es: 'cómo' },
  { de: 'warum', es: 'por qué' },
  { de: 'wie viel', es: 'cuánto' },
  { de: 'welcher / welche', es: 'cuál' },

  // ── Personalpronomen & Possessiv ───────────────────────────────────────────────
  { de: 'ich', es: 'yo' },
  { de: 'du', es: 'tú' },
  { de: 'er', es: 'él' },
  { de: 'sie (Einzahl)', es: 'ella' },
  { de: 'Sie (höflich)', es: 'usted' },
  { de: 'wir', es: 'nosotros' },
  { de: 'ihr', es: 'vosotros' },
  { de: 'sie (Mehrzahl)', es: 'ellos' },
  { de: 'mein', es: 'mi' },
  { de: 'dein', es: 'tu' },
  { de: 'sein / ihr', es: 'su' },
  { de: 'unser', es: 'nuestro' },

  // ── Zahlen 0–20 ──────────────────────────────────────────────────────────────
  { de: 'null', es: 'cero' },
  { de: 'eins', es: 'uno' },
  { de: 'zwei', es: 'dos' },
  { de: 'drei', es: 'tres' },
  { de: 'vier', es: 'cuatro' },
  { de: 'fünf', es: 'cinco' },
  { de: 'sechs', es: 'seis' },
  { de: 'sieben', es: 'siete' },
  { de: 'acht', es: 'ocho' },
  { de: 'neun', es: 'nueve' },
  { de: 'zehn', es: 'diez' },
  { de: 'elf', es: 'once' },
  { de: 'zwölf', es: 'doce' },
  { de: 'dreizehn', es: 'trece' },
  { de: 'vierzehn', es: 'catorce' },
  { de: 'fünfzehn', es: 'quince' },
  { de: 'sechzehn', es: 'dieciséis' },
  { de: 'siebzehn', es: 'diecisiete' },
  { de: 'achtzehn', es: 'dieciocho' },
  { de: 'neunzehn', es: 'diecinueve' },
  { de: 'zwanzig', es: 'veinte' },
  // ── Zahlen 30–100 & Ordnungszahlen ─────────────────────────────────────────────
  { de: 'einundzwanzig', es: 'veintiuno' },
  { de: 'dreißig', es: 'treinta' },
  { de: 'vierzig', es: 'cuarenta' },
  { de: 'fünfzig', es: 'cincuenta' },
  { de: 'sechzig', es: 'sesenta' },
  { de: 'siebzig', es: 'setenta' },
  { de: 'achtzig', es: 'ochenta' },
  { de: 'neunzig', es: 'noventa' },
  { de: 'hundert', es: 'cien' },
  { de: 'tausend', es: 'mil' },
  { de: 'erster', es: 'primero' },
  { de: 'zweiter', es: 'segundo' },
  { de: 'dritter', es: 'tercero' },
  { de: 'letzter', es: 'último' },
  { de: 'die Hälfte', es: 'la mitad' },
  { de: 'das Doppelte', es: 'el doble' },

  // ── Zeit, Tage, Monate, Jahreszeiten ────────────────────────────────────────────
  { de: 'Montag', es: 'el lunes' },
  { de: 'Dienstag', es: 'el martes' },
  { de: 'Mittwoch', es: 'el miércoles' },
  { de: 'Donnerstag', es: 'el jueves' },
  { de: 'Freitag', es: 'el viernes' },
  { de: 'Samstag', es: 'el sábado' },
  { de: 'Sonntag', es: 'el domingo' },
  { de: 'Januar', es: 'enero' },
  { de: 'Februar', es: 'febrero' },
  { de: 'März', es: 'marzo' },
  { de: 'April', es: 'abril' },
  { de: 'Mai', es: 'mayo' },
  { de: 'Juni', es: 'junio' },
  { de: 'Juli', es: 'julio' },
  { de: 'August', es: 'agosto' },
  { de: 'September', es: 'septiembre' },
  { de: 'Oktober', es: 'octubre' },
  { de: 'November', es: 'noviembre' },
  { de: 'Dezember', es: 'diciembre' },
  { de: 'der Frühling', es: 'la primavera' },
  { de: 'der Sommer', es: 'el verano' },
  { de: 'der Herbst', es: 'el otoño' },
  { de: 'der Winter', es: 'el invierno' },
  { de: 'heute', es: 'hoy' },
  { de: 'morgen', es: 'mañana' },
  { de: 'gestern', es: 'ayer' },
  { de: 'jetzt', es: 'ahora' },
  { de: 'später', es: 'más tarde' },
  { de: 'früher / vorher', es: 'antes' },
  { de: 'immer', es: 'siempre' },
  { de: 'nie / niemals', es: 'nunca' },
  { de: 'manchmal', es: 'a veces' },
  { de: 'oft', es: 'a menudo' },
  { de: 'bald', es: 'pronto' },
  { de: 'schon / bereits', es: 'ya' },
  { de: 'noch', es: 'todavía' },
  { de: 'die Sekunde', es: 'el segundo' },
  { de: 'die Minute', es: 'el minuto' },
  { de: 'die Stunde', es: 'la hora' },
  { de: 'der Tag', es: 'el día' },
  { de: 'die Woche', es: 'la semana' },
  { de: 'der Monat', es: 'el mes' },
  { de: 'das Jahr', es: 'el año' },
  { de: 'der Morgen', es: 'la mañana' },
  { de: 'der Nachmittag', es: 'la tarde' },
  { de: 'die Nacht', es: 'la noche' },
  { de: 'das Wochenende', es: 'el fin de semana' },

  // ── Farben ───────────────────────────────────────────────────────────────────
  { de: 'rot', es: 'rojo' },
  { de: 'blau', es: 'azul' },
  { de: 'grün', es: 'verde' },
  { de: 'gelb', es: 'amarillo' },
  { de: 'schwarz', es: 'negro' },
  { de: 'weiß', es: 'blanco' },
  { de: 'grau', es: 'gris' },
  { de: 'orange', es: 'naranja' },
  { de: 'lila / violett', es: 'morado' },
  { de: 'rosa', es: 'rosa' },
  { de: 'braun', es: 'marrón' },

  // ── Familie & Personen ─────────────────────────────────────────────────────────
  { de: 'die Mutter', es: 'la madre' },
  { de: 'der Vater', es: 'el padre' },
  { de: 'die Eltern', es: 'los padres' },
  { de: 'die Tochter', es: 'la hija' },
  { de: 'der Sohn', es: 'el hijo' },
  { de: 'die Kinder', es: 'los hijos' },
  { de: 'die Schwester', es: 'la hermana' },
  { de: 'der Bruder', es: 'el hermano' },
  { de: 'die Großmutter', es: 'la abuela' },
  { de: 'der Großvater', es: 'el abuelo' },
  { de: 'die Tante', es: 'la tía' },
  { de: 'der Onkel', es: 'el tío' },
  { de: 'die Cousine', es: 'la prima' },
  { de: 'der Cousin', es: 'el primo' },
  { de: 'die Ehefrau', es: 'la esposa' },
  { de: 'der Ehemann', es: 'el marido' },
  { de: 'der Freund / die Freundin (Partner)', es: 'el novio / la novia' },
  { de: 'der Freund / die Freundin', es: 'el amigo / la amiga' },
  { de: 'der Nachbar', es: 'el vecino' },
  { de: 'der Kollege', es: 'el compañero' },
  { de: 'das Baby', es: 'el bebé' },
  { de: 'das Kind', es: 'el niño' },
  { de: 'die Frau', es: 'la mujer' },
  { de: 'der Mann', es: 'el hombre' },
  { de: 'die Person', es: 'la persona' },
  { de: 'die Leute', es: 'la gente' },
  { de: 'der Name', es: 'el nombre' },

  // ── Körper ─────────────────────────────────────────────────────────────────────
  { de: 'der Kopf', es: 'la cabeza' },
  { de: 'das Haar', es: 'el pelo' },
  { de: 'das Gesicht', es: 'la cara' },
  { de: 'das Auge', es: 'el ojo' },
  { de: 'die Nase', es: 'la nariz' },
  { de: 'der Mund', es: 'la boca' },
  { de: 'das Ohr', es: 'la oreja' },
  { de: 'der Zahn', es: 'el diente' },
  { de: 'der Hals', es: 'el cuello' },
  { de: 'der Arm', es: 'el brazo' },
  { de: 'die Hand', es: 'la mano' },
  { de: 'der Finger', es: 'el dedo' },
  { de: 'das Bein', es: 'la pierna' },
  { de: 'der Fuß', es: 'el pie' },
  { de: 'der Bauch', es: 'el estómago' },
  { de: 'der Rücken', es: 'la espalda' },
  { de: 'das Herz', es: 'el corazón' },
  { de: 'die Haut', es: 'la piel' },

  // ── Essen & Trinken ────────────────────────────────────────────────────────────
  { de: 'das Essen', es: 'la comida' },
  { de: 'das Frühstück', es: 'el desayuno' },
  { de: 'das Mittagessen', es: 'el almuerzo' },
  { de: 'das Abendessen', es: 'la cena' },
  { de: 'das Wasser', es: 'el agua' },
  { de: 'der Kaffee', es: 'el café' },
  { de: 'der Tee', es: 'el té' },
  { de: 'der Saft', es: 'el zumo' },
  { de: 'die Milch', es: 'la leche' },
  { de: 'das Bier', es: 'la cerveza' },
  { de: 'der Wein', es: 'el vino' },
  { de: 'das Brot', es: 'el pan' },
  { de: 'die Butter', es: 'la mantequilla' },
  { de: 'der Käse', es: 'el queso' },
  { de: 'das Ei', es: 'el huevo' },
  { de: 'das Fleisch', es: 'la carne' },
  { de: 'der Fisch', es: 'el pescado' },
  { de: 'das Hühnchen', es: 'el pollo' },
  { de: 'der Schinken', es: 'el jamón' },
  { de: 'das Gemüse', es: 'las verduras' },
  { de: 'die Kartoffel', es: 'la patata' },
  { de: 'die Tomate', es: 'el tomate' },
  { de: 'die Zwiebel', es: 'la cebolla' },
  { de: 'der Salat', es: 'la ensalada' },
  { de: 'der Reis', es: 'el arroz' },
  { de: 'die Nudeln', es: 'la pasta' },
  { de: 'das Obst', es: 'la fruta' },
  { de: 'der Apfel', es: 'la manzana' },
  { de: 'die Banane', es: 'el plátano' },
  { de: 'die Orange', es: 'la naranja' },
  { de: 'die Zitrone', es: 'el limón' },
  { de: 'der Zucker', es: 'el azúcar' },
  { de: 'das Salz', es: 'la sal' },
  { de: 'das Öl', es: 'el aceite' },
  { de: 'die Suppe', es: 'la sopa' },
  { de: 'der Kuchen', es: 'el pastel' },
  { de: 'das Eis', es: 'el helado' },
  { de: 'die Schokolade', es: 'el chocolate' },

  // ── Zuhause, Möbel & Küche ─────────────────────────────────────────────────────
  { de: 'das Haus', es: 'la casa' },
  { de: 'die Wohnung', es: 'el piso' },
  { de: 'das Zimmer', es: 'la habitación' },
  { de: 'die Küche', es: 'la cocina' },
  { de: 'das Badezimmer', es: 'el baño' },
  { de: 'das Wohnzimmer', es: 'el salón' },
  { de: 'das Schlafzimmer', es: 'el dormitorio' },
  { de: 'der Garten', es: 'el jardín' },
  { de: 'die Tür', es: 'la puerta' },
  { de: 'das Fenster', es: 'la ventana' },
  { de: 'die Wand', es: 'la pared' },
  { de: 'der Boden', es: 'el suelo' },
  { de: 'der Tisch', es: 'la mesa' },
  { de: 'der Stuhl', es: 'la silla' },
  { de: 'das Sofa', es: 'el sofá' },
  { de: 'das Bett', es: 'la cama' },
  { de: 'der Schrank', es: 'el armario' },
  { de: 'die Lampe', es: 'la lámpara' },
  { de: 'der Schlüssel', es: 'la llave' },
  { de: 'der Teller', es: 'el plato' },
  { de: 'das Glas', es: 'el vaso' },
  { de: 'die Tasse', es: 'la taza' },
  { de: 'die Flasche', es: 'la botella' },
  { de: 'das Messer', es: 'el cuchillo' },
  { de: 'die Gabel', es: 'el tenedor' },
  { de: 'der Löffel', es: 'la cuchara' },

  // ── Stadt & Orte ───────────────────────────────────────────────────────────────
  { de: 'die Stadt', es: 'la ciudad' },
  { de: 'das Dorf', es: 'el pueblo' },
  { de: 'das Land', es: 'el país' },
  { de: 'die Straße', es: 'la calle' },
  { de: 'der Platz', es: 'la plaza' },
  { de: 'das Geschäft / der Laden', es: 'la tienda' },
  { de: 'der Supermarkt', es: 'el supermercado' },
  { de: 'der Markt', es: 'el mercado' },
  { de: 'das Restaurant', es: 'el restaurante' },
  { de: 'die Bar / das Café', es: 'el bar' },
  { de: 'das Hotel', es: 'el hotel' },
  { de: 'der Bahnhof', es: 'la estación de tren' },
  { de: 'der Flughafen', es: 'el aeropuerto' },
  { de: 'das Krankenhaus', es: 'el hospital' },
  { de: 'die Apotheke', es: 'la farmacia' },
  { de: 'die Bank', es: 'el banco' },
  { de: 'die Schule', es: 'el colegio' },
  { de: 'die Kirche', es: 'la iglesia' },
  { de: 'das Museum', es: 'el museo' },
  { de: 'der Park', es: 'el parque' },
  { de: 'der Strand', es: 'la playa' },
  { de: 'das Kino', es: 'el cine' },

  // ── Reisen & Transport ──────────────────────────────────────────────────────────
  { de: 'die Reise', es: 'el viaje' },
  { de: 'der Koffer', es: 'la maleta' },
  { de: 'der Pass', es: 'el pasaporte' },
  { de: 'das Ticket / die Fahrkarte', es: 'el billete' },
  { de: 'die Reservierung', es: 'la reserva' },
  { de: 'der Tourist', es: 'el turista' },
  { de: 'das Auto', es: 'el coche' },
  { de: 'der Bus', es: 'el autobús' },
  { de: 'die U-Bahn', es: 'el metro' },
  { de: 'das Taxi', es: 'el taxi' },
  { de: 'das Flugzeug', es: 'el avión' },
  { de: 'der Zug', es: 'el tren' },
  { de: 'das Fahrrad', es: 'la bicicleta' },
  { de: 'rechts', es: 'a la derecha' },
  { de: 'links', es: 'a la izquierda' },
  { de: 'geradeaus', es: 'todo recto' },
  { de: 'nah', es: 'cerca' },
  { de: 'weit', es: 'lejos' },

  // ── Kleidung ─────────────────────────────────────────────────────────────────────
  { de: 'die Kleidung', es: 'la ropa' },
  { de: 'das Hemd', es: 'la camisa' },
  { de: 'die Hose', es: 'los pantalones' },
  { de: 'das Kleid', es: 'el vestido' },
  { de: 'der Rock', es: 'la falda' },
  { de: 'die Jacke', es: 'la chaqueta' },
  { de: 'der Schuh', es: 'el zapato' },
  { de: 'die Socke', es: 'el calcetín' },
  { de: 'der Hut', es: 'el sombrero' },
  { de: 'die Brille', es: 'las gafas' },

  // ── Grundverben (regelmäßig) ─────────────────────────────────────────────────────
  { de: 'sprechen', es: 'hablar' },
  { de: 'arbeiten', es: 'trabajar' },
  { de: 'studieren / lernen', es: 'estudiar' },
  { de: 'kaufen', es: 'comprar' },
  { de: 'bezahlen', es: 'pagar' },
  { de: 'anschauen', es: 'mirar' },
  { de: 'hören / zuhören', es: 'escuchar' },
  { de: 'fragen', es: 'preguntar' },
  { de: 'antworten', es: 'contestar' },
  { de: 'anrufen / nennen', es: 'llamar' },
  { de: 'warten', es: 'esperar' },
  { de: 'helfen', es: 'ayudar' },
  { de: 'brauchen', es: 'necesitar' },
  { de: 'tragen / bringen', es: 'llevar' },
  { de: 'tanzen', es: 'bailar' },
  { de: 'singen', es: 'cantar' },
  { de: 'kochen', es: 'cocinar' },
  { de: 'reisen', es: 'viajar' },
  { de: 'lieben', es: 'amar' },
  { de: 'nehmen / trinken', es: 'tomar' },
  { de: 'essen', es: 'comer' },
  { de: 'trinken', es: 'beber' },
  { de: 'lernen / erfahren', es: 'aprender' },
  { de: 'lesen', es: 'leer' },
  { de: 'laufen / rennen', es: 'correr' },
  { de: 'verstehen', es: 'comprender' },
  { de: 'leben / wohnen', es: 'vivir' },
  { de: 'schreiben', es: 'escribir' },
  { de: 'öffnen', es: 'abrir' },
  { de: 'empfangen / bekommen', es: 'recibir' },

  // ── Grundverben (unregelmäßig & häufig) ──────────────────────────────────────────
  { de: 'sein (Eigenschaft)', es: 'ser' },
  { de: 'sein (Zustand/Ort)', es: 'estar' },
  { de: 'haben', es: 'tener' },
  { de: 'es gibt', es: 'haber' },
  { de: 'machen / tun', es: 'hacer' },
  { de: 'gehen', es: 'ir' },
  { de: 'kommen', es: 'venir' },
  { de: 'sagen', es: 'decir' },
  { de: 'sehen', es: 'ver' },
  { de: 'geben', es: 'dar' },
  { de: 'wissen', es: 'saber' },
  { de: 'kennen', es: 'conocer' },
  { de: 'können', es: 'poder' },
  { de: 'wollen / lieben', es: 'querer' },
  { de: 'müssen / schulden', es: 'deber' },
  { de: 'denken', es: 'pensar' },
  { de: 'glauben', es: 'creer' },
  { de: 'finden', es: 'encontrar' },
  { de: 'schlafen', es: 'dormir' },
  { de: 'spielen', es: 'jugar' },
  { de: 'beginnen', es: 'empezar' },
  { de: 'beenden / aufhören', es: 'terminar' },
  { de: 'heißen', es: 'llamarse' },
  { de: 'sich setzen', es: 'sentarse' },
  { de: 'aufstehen', es: 'levantarse' },

  // ── Einfache Adjektive ────────────────────────────────────────────────────────────
  { de: 'groß', es: 'grande' },
  { de: 'klein', es: 'pequeño' },
  { de: 'lang', es: 'largo' },
  { de: 'kurz', es: 'corto' },
  { de: 'hoch / groß (Person)', es: 'alto' },
  { de: 'niedrig / klein (Person)', es: 'bajo' },
  { de: 'gut', es: 'bueno' },
  { de: 'schlecht', es: 'malo' },
  { de: 'schön', es: 'bonito' },
  { de: 'hässlich', es: 'feo' },
  { de: 'neu', es: 'nuevo' },
  { de: 'alt', es: 'viejo' },
  { de: 'jung', es: 'joven' },
  { de: 'schnell', es: 'rápido' },
  { de: 'langsam', es: 'lento' },
  { de: 'einfach', es: 'fácil' },
  { de: 'schwierig', es: 'difícil' },
  { de: 'teuer', es: 'caro' },
  { de: 'günstig / billig', es: 'barato' },
  { de: 'warm / heiß', es: 'caliente' },
  { de: 'kalt', es: 'frío' },
  { de: 'sauber', es: 'limpio' },
  { de: 'schmutzig', es: 'sucio' },
  { de: 'voll', es: 'lleno' },
  { de: 'leer', es: 'vacío' },
  { de: 'glücklich', es: 'feliz' },
  { de: 'traurig', es: 'triste' },
  { de: 'müde', es: 'cansado' },
  { de: 'krank', es: 'enfermo' },
  { de: 'wichtig', es: 'importante' },
  { de: 'gleich', es: 'igual' },
  { de: 'anders / verschieden', es: 'diferente' },
  { de: 'viel', es: 'mucho' },
  { de: 'wenig', es: 'poco' },
  { de: 'mehr', es: 'más' },
  { de: 'weniger', es: 'menos' },

  // ── Natur & Wetter ──────────────────────────────────────────────────────────────
  { de: 'die Natur', es: 'la naturaleza' },
  { de: 'der Baum', es: 'el árbol' },
  { de: 'die Blume', es: 'la flor' },
  { de: 'der Berg', es: 'la montaña' },
  { de: 'der Fluss', es: 'el río' },
  { de: 'das Meer', es: 'el mar' },
  { de: 'der Himmel', es: 'el cielo' },
  { de: 'die Sonne', es: 'el sol' },
  { de: 'der Mond', es: 'la luna' },
  { de: 'der Stern', es: 'la estrella' },
  { de: 'die Wolke', es: 'la nube' },
  { de: 'der Regen', es: 'la lluvia' },
  { de: 'der Schnee', es: 'la nieve' },
  { de: 'der Wind', es: 'el viento' },
  { de: 'das Feuer', es: 'el fuego' },
  { de: 'die Erde', es: 'la tierra' },

  // ── Tiere ─────────────────────────────────────────────────────────────────────────
  { de: 'das Tier', es: 'el animal' },
  { de: 'der Hund', es: 'el perro' },
  { de: 'die Katze', es: 'el gato' },
  { de: 'das Pferd', es: 'el caballo' },
  { de: 'der Vogel', es: 'el pájaro' },
  { de: 'die Kuh', es: 'la vaca' },
  { de: 'das Schwein', es: 'el cerdo' },
  { de: 'der Fisch (Tier)', es: 'el pez' },

  // ── Schule & Bildung ──────────────────────────────────────────────────────────────
  { de: 'das Buch', es: 'el libro' },
  { de: 'das Heft', es: 'el cuaderno' },
  { de: 'der Stift', es: 'el bolígrafo' },
  { de: 'das Papier', es: 'el papel' },
  { de: 'der Schüler', es: 'el alumno' },
  { de: 'der Lehrer', es: 'el profesor' },
  { de: 'die Klasse / der Unterricht', es: 'la clase' },
  { de: 'die Prüfung', es: 'el examen' },
  { de: 'die Hausaufgabe', es: 'la tarea' },
  { de: 'die Sprache', es: 'el idioma' },
  { de: 'das Wort', es: 'la palabra' },
  { de: 'der Satz', es: 'la frase' },
  { de: 'die Frage', es: 'la pregunta' },
  { de: 'die Antwort', es: 'la respuesta' },

  // ── Arbeit & Berufe ───────────────────────────────────────────────────────────────
  { de: 'die Arbeit', es: 'el trabajo' },
  { de: 'der Beruf', es: 'la profesión' },
  { de: 'das Büro', es: 'la oficina' },
  { de: 'der Chef / die Chefin', es: 'el jefe' },
  { de: 'die Firma', es: 'la empresa' },
  { de: 'der Arzt / die Ärztin', es: 'el médico' },
  { de: 'der Lehrer (Beruf)', es: 'el maestro' },
  { de: 'der Koch', es: 'el cocinero' },
  { de: 'der Kellner', es: 'el camarero' },
  { de: 'der Verkäufer', es: 'el vendedor' },
  { de: 'der Urlaub / die Ferien', es: 'las vacaciones' },
  { de: 'der Termin', es: 'la cita' },

  // ── Gesundheit ─────────────────────────────────────────────────────────────────────
  { de: 'die Gesundheit', es: 'la salud' },
  { de: 'der Schmerz', es: 'el dolor' },
  { de: 'das Fieber', es: 'la fiebre' },
  { de: 'die Krankheit', es: 'la enfermedad' },
  { de: 'das Medikament', es: 'el medicamento' },
  { de: 'die Tablette', es: 'la pastilla' },
  { de: 'der Notfall', es: 'la emergencia' },
  { de: 'der Schlaf', es: 'el sueño' },

  // ── Technologie ─────────────────────────────────────────────────────────────────────
  { de: 'der Computer', es: 'el ordenador' },
  { de: 'das Handy', es: 'el móvil' },
  { de: 'das Internet', es: 'internet' },
  { de: 'die E-Mail', es: 'el correo electrónico' },
  { de: 'das Foto', es: 'la foto' },
  { de: 'das Video', es: 'el vídeo' },
  { de: 'das Passwort', es: 'la contraseña' },
  { de: 'der Bildschirm', es: 'la pantalla' },

  // ── Geld & Einkaufen ────────────────────────────────────────────────────────────────
  { de: 'das Geld', es: 'el dinero' },
  { de: 'der Preis', es: 'el precio' },
  { de: 'die Rechnung', es: 'la cuenta' },
  { de: 'die Kreditkarte', es: 'la tarjeta de crédito' },
  { de: 'das Bargeld', es: 'el efectivo' },
  { de: 'das Angebot', es: 'la oferta' },
  { de: 'der Rabatt', es: 'el descuento' },

  // ── Emotionen & Charakter ────────────────────────────────────────────────────────────
  { de: 'die Liebe', es: 'el amor' },
  { de: 'die Freude', es: 'la alegría' },
  { de: 'die Angst', es: 'el miedo' },
  { de: 'die Hoffnung', es: 'la esperanza' },
  { de: 'freundlich', es: 'amable' },
  { de: 'nett / sympathisch', es: 'simpático' },
  { de: 'höflich', es: 'educado' },
  { de: 'ehrlich', es: 'honesto' },
  { de: 'mutig', es: 'valiente' },
  { de: 'schüchtern', es: 'tímido' },
  { de: 'geduldig', es: 'paciente' },
  { de: 'lustig / komisch', es: 'gracioso' },
  { de: 'intelligent', es: 'inteligente' },

  // ── Nützliche kleine Wörter (Adverbien, Präpositionen, Verbindungen) ──────────────────
  { de: 'und', es: 'y' },
  { de: 'oder', es: 'o' },
  { de: 'aber', es: 'pero' },
  { de: 'weil', es: 'porque' },
  { de: 'wenn / falls', es: 'si' },
  { de: 'auch', es: 'también' },
  { de: 'auch nicht', es: 'tampoco' },
  { de: 'sehr', es: 'muy' },
  { de: 'ein bisschen', es: 'un poco' },
  { de: 'gut / na gut', es: 'vale' },
  { de: 'natürlich / klar', es: 'claro' },
  { de: 'fast', es: 'casi' },
  { de: 'nur', es: 'solo' },
  { de: 'sogar', es: 'incluso' },
  { de: 'hier', es: 'aquí' },
  { de: 'dort', es: 'allí' },
  { de: 'oben', es: 'arriba' },
  { de: 'unten', es: 'abajo' },
  { de: 'drinnen', es: 'dentro' },
  { de: 'draußen', es: 'fuera' },
  { de: 'in / auf', es: 'en' },
  { de: 'von / aus', es: 'de' },
  { de: 'mit', es: 'con' },
  { de: 'ohne', es: 'sin' },
  { de: 'für', es: 'para' },
  { de: 'zwischen', es: 'entre' },
  { de: 'gegen', es: 'contra' },
  { de: 'unter', es: 'debajo de' },
  { de: 'über / auf', es: 'sobre' },
  { de: 'bis', es: 'hasta' },
  { de: 'während', es: 'durante' },
  { de: 'nach', es: 'después de' },
  { de: 'vor (zeitlich)', es: 'antes de' },
];

// Strip a leading article so "el día" and "día" are treated as the same word.
function key(es: string): string {
  return es
    .toLowerCase()
    .trim()
    .replace(/^(el|la|los|las|un|una|unos|unas)\s+/i, '')
    .trim();
}

// Dedupe by normalized Spanish so an accidental repeat never yields a double card.
const seen = new Set<string>();
export const STARTER_VOCAB: CatalogWord[] = RAW.filter(w => {
  const k = key(w.es);
  if (seen.has(k)) return false;
  seen.add(k);
  return true;
});
