export interface CatalogWord {
  de: string;
  es: string;
}

export const VOCAB_CATALOG: CatalogWord[] = [
  // ── Häufige Verben ───────────────────────────────────────────────────────
  { de: 'sein (Eigenschaft)', es: 'ser' },
  { de: 'sein (Zustand/Ort)', es: 'estar' },
  { de: 'haben', es: 'tener' },
  { de: 'machen / tun', es: 'hacer' },
  { de: 'können', es: 'poder' },
  { de: 'sagen', es: 'decir' },
  { de: 'gehen', es: 'ir' },
  { de: 'sehen', es: 'ver' },
  { de: 'geben', es: 'dar' },
  { de: 'wissen', es: 'saber' },
  { de: 'wollen / lieben', es: 'querer' },
  { de: 'kommen', es: 'venir' },
  { de: 'legen / stellen', es: 'poner' },
  { de: 'sprechen', es: 'hablar' },
  { de: 'hinterlassen / lassen', es: 'dejar' },
  { de: 'folgen', es: 'seguir' },
  { de: 'ankommen / erreichen', es: 'llegar' },
  { de: 'kennen', es: 'conocer' },
  { de: 'leben / wohnen', es: 'vivir' },
  { de: 'nehmen', es: 'tomar' },
  { de: 'denken', es: 'pensar' },
  { de: 'fragen', es: 'preguntar' },
  { de: 'finden', es: 'encontrar' },
  { de: 'glauben', es: 'creer' },
  { de: 'tragen / bringen', es: 'llevar' },
  { de: 'anrufen / nennen', es: 'llamar' },
  { de: 'arbeiten', es: 'trabajar' },
  { de: 'lesen', es: 'leer' },
  { de: 'hören', es: 'escuchar' },
  { de: 'öffnen', es: 'abrir' },
  { de: 'schreiben', es: 'escribir' },
  { de: 'kaufen', es: 'comprar' },
  { de: 'essen', es: 'comer' },
  { de: 'trinken', es: 'beber' },
  { de: 'schlafen', es: 'dormir' },
  { de: 'spielen', es: 'jugar' },
  { de: 'beginnen', es: 'empezar' },
  { de: 'helfen', es: 'ayudar' },
  { de: 'schauen / anschauen', es: 'mirar' },
  { de: 'brauchen', es: 'necesitar' },
  { de: 'lieben', es: 'amar' },
  { de: 'rennen / laufen', es: 'correr' },
  { de: 'lernen', es: 'aprender' },
  { de: 'vergessen', es: 'olvidar' },
  { de: 'erinnern', es: 'recordar' },
  { de: 'bezahlen', es: 'pagar' },
  { de: 'verlieren', es: 'perder' },
  { de: 'zeigen', es: 'mostrar' },
  { de: 'verstehen', es: 'entender' },
  { de: 'erklären', es: 'explicar' },
  { de: 'warten', es: 'esperar' },
  { de: 'versuchen', es: 'intentar' },
  { de: 'reisen', es: 'viajar' },
  { de: 'tanzen', es: 'bailar' },
  { de: 'singen', es: 'cantar' },
  { de: 'kochen', es: 'cocinar' },
  { de: 'schicken / senden', es: 'enviar' },
  { de: 'antworten', es: 'contestar' },
  { de: 'entscheiden', es: 'decidir' },
  { de: 'passieren / geschehen', es: 'pasar' },
  { de: 'bedeuten', es: 'significar' },
  { de: 'heiraten', es: 'casarse' },
  { de: 'sterben', es: 'morir' },
  { de: 'gewinnen', es: 'ganar' },
  { de: 'empfehlen', es: 'recomendar' },
  { de: 'erlauben', es: 'permitir' },
  { de: 'sich setzen', es: 'sentarse' },
  { de: 'aufstehen', es: 'levantarse' },
  { de: 'waschen', es: 'lavar' },
  { de: 'malen / anstreichen', es: 'pintar' },
  { de: 'bauen', es: 'construir' },
  { de: 'zählen', es: 'contar' },
  { de: 'fehlen / fehlen lassen', es: 'faltar' },
  { de: 'gehören', es: 'pertenecer' },
  { de: 'sich interessieren', es: 'interesarse' },
  { de: 'landen', es: 'aterrizar' },
  { de: 'steigen', es: 'subir' },
  { de: 'fallen', es: 'caer' },
  { de: 'lächeln', es: 'sonreír' },
  { de: 'weinen', es: 'llorar' },
  { de: 'lachen', es: 'reír' },
  { de: 'besuchen', es: 'visitar' },
  { de: 'telefonieren', es: 'llamar por teléfono' },
  { de: 'fahren (Auto)', es: 'conducir' },
  { de: 'fliegen', es: 'volar' },
  { de: 'schwimmen', es: 'nadar' },
  { de: 'drücken', es: 'empujar' },
  { de: 'ziehen', es: 'tirar' },
  { de: 'buchen / reservieren', es: 'reservar' },
  { de: 'teilen', es: 'compartir' },
  { de: 'genießen', es: 'disfrutar' },
  { de: 'verbessern', es: 'mejorar' },
  { de: 'verändern', es: 'cambiar' },
  { de: 'sich treffen', es: 'reunirse' },

  // ── Körper ───────────────────────────────────────────────────────────────
  { de: 'der Kopf', es: 'la cabeza' },
  { de: 'das Haar', es: 'el pelo' },
  { de: 'das Gesicht', es: 'la cara' },
  { de: 'das Auge', es: 'el ojo' },
  { de: 'die Nase', es: 'la nariz' },
  { de: 'der Mund', es: 'la boca' },
  { de: 'das Ohr', es: 'la oreja' },
  { de: 'der Hals', es: 'el cuello' },
  { de: 'die Schulter', es: 'el hombro' },
  { de: 'der Arm', es: 'el brazo' },
  { de: 'die Hand', es: 'la mano' },
  { de: 'der Finger', es: 'el dedo' },
  { de: 'die Brust', es: 'el pecho' },
  { de: 'der Bauch', es: 'el estómago' },
  { de: 'der Rücken', es: 'la espalda' },
  { de: 'das Bein', es: 'la pierna' },
  { de: 'das Knie', es: 'la rodilla' },
  { de: 'der Fuß', es: 'el pie' },
  { de: 'die Haut', es: 'la piel' },
  { de: 'das Blut', es: 'la sangre' },
  { de: 'das Herz', es: 'el corazón' },
  { de: 'die Lunge', es: 'el pulmón' },
  { de: 'das Gehirn', es: 'el cerebro' },
  { de: 'der Zahn', es: 'el diente' },
  { de: 'die Lippe', es: 'el labio' },

  // ── Familie & Personen ───────────────────────────────────────────────────
  { de: 'die Mutter', es: 'la madre' },
  { de: 'der Vater', es: 'el padre' },
  { de: 'die Eltern', es: 'los padres' },
  { de: 'die Tochter', es: 'la hija' },
  { de: 'der Sohn', es: 'el hijo' },
  { de: 'die Kinder', es: 'los hijos' },
  { de: 'die Schwester', es: 'la hermana' },
  { de: 'der Bruder', es: 'el hermano' },
  { de: 'die Großmutter', es: 'la abuela' },
  { de: 'der Großvater', es: 'el abuelo' },
  { de: 'die Tante', es: 'la tía' },
  { de: 'der Onkel', es: 'el tío' },
  { de: 'die Cousine', es: 'la prima' },
  { de: 'der Cousin', es: 'el primo' },
  { de: 'die Nichte', es: 'la sobrina' },
  { de: 'der Neffe', es: 'el sobrino' },
  { de: 'die Frau / Ehefrau', es: 'la esposa' },
  { de: 'der Mann / Ehemann', es: 'el marido' },
  { de: 'der Freund / Freundin (partner)', es: 'el novio / la novia' },
  { de: 'der Freund / die Freundin', es: 'el amigo / la amiga' },
  { de: 'der Nachbar', es: 'el vecino' },
  { de: 'der Kollege', es: 'el compañero' },
  { de: 'das Baby', es: 'el bebé' },
  { de: 'das Kind', es: 'el niño' },
  { de: 'der Jugendliche', es: 'el joven' },
  { de: 'der Erwachsene', es: 'el adulto' },
  { de: 'die Person', es: 'la persona' },
  { de: 'der Mensch', es: 'el ser humano' },

  // ── Essen & Trinken ──────────────────────────────────────────────────────
  { de: 'das Brot', es: 'el pan' },
  { de: 'die Butter', es: 'la mantequilla' },
  { de: 'der Käse', es: 'el queso' },
  { de: 'das Ei', es: 'el huevo' },
  { de: 'die Milch', es: 'la leche' },
  { de: 'der Joghurt', es: 'el yogur' },
  { de: 'das Fleisch', es: 'la carne' },
  { de: 'der Fisch', es: 'el pescado' },
  { de: 'das Hühnchen', es: 'el pollo' },
  { de: 'das Schweinefleisch', es: 'el cerdo' },
  { de: 'das Rindfleisch', es: 'la ternera' },
  { de: 'der Schinken', es: 'el jamón' },
  { de: 'die Wurst', es: 'el embutido' },
  { de: 'das Gemüse', es: 'las verduras' },
  { de: 'die Kartoffel', es: 'la patata' },
  { de: 'die Tomate', es: 'el tomate' },
  { de: 'die Zwiebel', es: 'la cebolla' },
  { de: 'der Knoblauch', es: 'el ajo' },
  { de: 'die Karotte', es: 'la zanahoria' },
  { de: 'der Salat', es: 'la ensalada' },
  { de: 'die Bohne', es: 'el frijol' },
  { de: 'der Reis', es: 'el arroz' },
  { de: 'die Nudeln', es: 'la pasta' },
  { de: 'das Obst', es: 'la fruta' },
  { de: 'der Apfel', es: 'la manzana' },
  { de: 'die Birne', es: 'la pera' },
  { de: 'die Banane', es: 'el plátano' },
  { de: 'die Orange', es: 'la naranja' },
  { de: 'die Erdbeere', es: 'la fresa' },
  { de: 'die Traube', es: 'la uva' },
  { de: 'die Zitrone', es: 'el limón' },
  { de: 'die Wassermelone', es: 'la sandía' },
  { de: 'das Wasser', es: 'el agua' },
  { de: 'der Kaffee', es: 'el café' },
  { de: 'der Tee', es: 'el té' },
  { de: 'der Saft', es: 'el zumo' },
  { de: 'das Bier', es: 'la cerveza' },
  { de: 'der Wein', es: 'el vino' },
  { de: 'der Zucker', es: 'el azúcar' },
  { de: 'das Salz', es: 'la sal' },
  { de: 'der Pfeffer', es: 'la pimienta' },
  { de: 'das Öl', es: 'el aceite' },
  { de: 'die Soße', es: 'la salsa' },
  { de: 'die Suppe', es: 'la sopa' },
  { de: 'der Kuchen', es: 'el pastel' },
  { de: 'das Eis', es: 'el helado' },
  { de: 'die Schokolade', es: 'el chocolate' },
  { de: 'das Frühstück', es: 'el desayuno' },
  { de: 'das Mittagessen', es: 'el almuerzo' },
  { de: 'das Abendessen', es: 'la cena' },

  // ── Zuhause & Möbel ──────────────────────────────────────────────────────
  { de: 'das Haus', es: 'la casa' },
  { de: 'die Wohnung', es: 'el piso' },
  { de: 'das Zimmer', es: 'la habitación' },
  { de: 'die Küche', es: 'la cocina' },
  { de: 'das Badezimmer', es: 'el baño' },
  { de: 'das Wohnzimmer', es: 'el salón' },
  { de: 'das Schlafzimmer', es: 'el dormitorio' },
  { de: 'die Tür', es: 'la puerta' },
  { de: 'das Fenster', es: 'la ventana' },
  { de: 'die Treppe', es: 'la escalera' },
  { de: 'der Tisch', es: 'la mesa' },
  { de: 'der Stuhl', es: 'la silla' },
  { de: 'das Sofa', es: 'el sofá' },
  { de: 'das Bett', es: 'la cama' },
  { de: 'der Schrank', es: 'el armario' },
  { de: 'das Regal', es: 'la estantería' },
  { de: 'die Lampe', es: 'la lámpara' },
  { de: 'der Spiegel', es: 'el espejo' },
  { de: 'der Teppich', es: 'la alfombra' },
  { de: 'der Vorhang', es: 'la cortina' },
  { de: 'die Kühlschrank', es: 'el frigorífico' },
  { de: 'der Herd', es: 'la cocina (electrodoméstico)' },
  { de: 'die Waschmaschine', es: 'la lavadora' },
  { de: 'der Staubsauger', es: 'la aspiradora' },
  { de: 'der Schlüssel', es: 'la llave' },

  // ── Farben ───────────────────────────────────────────────────────────────
  { de: 'rot', es: 'rojo' },
  { de: 'blau', es: 'azul' },
  { de: 'grün', es: 'verde' },
  { de: 'gelb', es: 'amarillo' },
  { de: 'schwarz', es: 'negro' },
  { de: 'weiß', es: 'blanco' },
  { de: 'grau', es: 'gris' },
  { de: 'orange', es: 'naranja' },
  { de: 'lila / violett', es: 'morado' },
  { de: 'rosa', es: 'rosa' },
  { de: 'braun', es: 'marrón' },
  { de: 'beige', es: 'beige' },
  { de: 'golden', es: 'dorado' },
  { de: 'silbern', es: 'plateado' },

  // ── Zeit ─────────────────────────────────────────────────────────────────
  { de: 'die Sekunde', es: 'el segundo' },
  { de: 'die Minute', es: 'el minuto' },
  { de: 'die Stunde', es: 'la hora' },
  { de: 'der Tag', es: 'el día' },
  { de: 'die Woche', es: 'la semana' },
  { de: 'der Monat', es: 'el mes' },
  { de: 'das Jahr', es: 'el año' },
  { de: 'heute', es: 'hoy' },
  { de: 'gestern', es: 'ayer' },
  { de: 'morgen', es: 'mañana' },
  { de: 'jetzt', es: 'ahora' },
  { de: 'später', es: 'más tarde' },
  { de: 'früher / vorher', es: 'antes' },
  { de: 'immer', es: 'siempre' },
  { de: 'nie / niemals', es: 'nunca' },
  { de: 'manchmal', es: 'a veces' },
  { de: 'oft', es: 'a menudo' },
  { de: 'selten', es: 'raramente' },
  { de: 'bald', es: 'pronto' },
  { de: 'schon / bereits', es: 'ya' },
  { de: 'noch', es: 'todavía' },
  { de: 'der Morgen', es: 'la mañana' },
  { de: 'der Nachmittag', es: 'la tarde' },
  { de: 'der Abend', es: 'la noche' },
  { de: 'die Nacht', es: 'la noche' },
  { de: 'das Wochenende', es: 'el fin de semana' },
  { de: 'Montag', es: 'el lunes' },
  { de: 'Dienstag', es: 'el martes' },
  { de: 'Mittwoch', es: 'el miércoles' },
  { de: 'Donnerstag', es: 'el jueves' },
  { de: 'Freitag', es: 'el viernes' },
  { de: 'Samstag', es: 'el sábado' },
  { de: 'Sonntag', es: 'el domingo' },
  { de: 'Januar', es: 'enero' },
  { de: 'Februar', es: 'febrero' },
  { de: 'März', es: 'marzo' },
  { de: 'April', es: 'abril' },
  { de: 'Mai', es: 'mayo' },
  { de: 'Juni', es: 'junio' },
  { de: 'Juli', es: 'julio' },
  { de: 'August', es: 'agosto' },
  { de: 'September', es: 'septiembre' },
  { de: 'Oktober', es: 'octubre' },
  { de: 'November', es: 'noviembre' },
  { de: 'Dezember', es: 'diciembre' },

  // ── Natur & Wetter ───────────────────────────────────────────────────────
  { de: 'die Natur', es: 'la naturaleza' },
  { de: 'der Baum', es: 'el árbol' },
  { de: 'die Blume', es: 'la flor' },
  { de: 'das Gras', es: 'la hierba' },
  { de: 'der Wald', es: 'el bosque' },
  { de: 'der Berg', es: 'la montaña' },
  { de: 'das Tal', es: 'el valle' },
  { de: 'der Fluss', es: 'el río' },
  { de: 'der See', es: 'el lago' },
  { de: 'das Meer', es: 'el mar' },
  { de: 'der Strand', es: 'la playa' },
  { de: 'die Insel', es: 'la isla' },
  { de: 'die Küste', es: 'la costa' },
  { de: 'die Wüste', es: 'el desierto' },
  { de: 'der Himmel', es: 'el cielo' },
  { de: 'die Sonne', es: 'el sol' },
  { de: 'der Mond', es: 'la luna' },
  { de: 'der Stern', es: 'la estrella' },
  { de: 'die Wolke', es: 'la nube' },
  { de: 'der Regen', es: 'la lluvia' },
  { de: 'der Schnee', es: 'la nieve' },
  { de: 'der Wind', es: 'el viento' },
  { de: 'das Gewitter', es: 'la tormenta' },
  { de: 'der Blitz', es: 'el rayo' },
  { de: 'der Nebel', es: 'la niebla' },
  { de: 'der Frühling', es: 'la primavera' },
  { de: 'der Sommer', es: 'el verano' },
  { de: 'der Herbst', es: 'el otoño' },
  { de: 'der Winter', es: 'el invierno' },
  { de: 'die Temperatur', es: 'la temperatura' },

  // ── Stadt & Orte ─────────────────────────────────────────────────────────
  { de: 'die Stadt', es: 'la ciudad' },
  { de: 'das Dorf', es: 'el pueblo' },
  { de: 'das Land', es: 'el país' },
  { de: 'die Straße', es: 'la calle' },
  { de: 'der Platz', es: 'la plaza' },
  { de: 'die Brücke', es: 'el puente' },
  { de: 'das Geschäft / der Laden', es: 'la tienda' },
  { de: 'der Supermarkt', es: 'el supermercado' },
  { de: 'der Markt', es: 'el mercado' },
  { de: 'der Bahnhof', es: 'la estación de tren' },
  { de: 'der Flughafen', es: 'el aeropuerto' },
  { de: 'das Hotel', es: 'el hotel' },
  { de: 'das Restaurant', es: 'el restaurante' },
  { de: 'die Bar / das Café', es: 'el bar' },
  { de: 'die Kirche', es: 'la iglesia' },
  { de: 'das Museum', es: 'el museo' },
  { de: 'das Krankenhaus', es: 'el hospital' },
  { de: 'die Apotheke', es: 'la farmacia' },
  { de: 'die Bank', es: 'el banco' },
  { de: 'das Büro', es: 'la oficina' },
  { de: 'die Schule', es: 'el colegio' },
  { de: 'die Universität', es: 'la universidad' },
  { de: 'die Bibliothek', es: 'la biblioteca' },
  { de: 'das Theater', es: 'el teatro' },
  { de: 'das Kino', es: 'el cine' },
  { de: 'der Park', es: 'el parque' },
  { de: 'der Friedhof', es: 'el cementerio' },
  { de: 'das Rathaus', es: 'el ayuntamiento' },
  { de: 'die Post', es: 'la oficina de correos' },
  { de: 'die Polizei', es: 'la policía' },

  // ── Arbeit & Berufe ──────────────────────────────────────────────────────
  { de: 'die Arbeit', es: 'el trabajo' },
  { de: 'der Beruf', es: 'la profesión' },
  { de: 'das Gehalt', es: 'el sueldo' },
  { de: 'der Chef / die Chefin', es: 'el jefe' },
  { de: 'der Mitarbeiter', es: 'el empleado' },
  { de: 'die Firma', es: 'la empresa' },
  { de: 'die Besprechung', es: 'la reunión' },
  { de: 'das Projekt', es: 'el proyecto' },
  { de: 'der Termin', es: 'la cita' },
  { de: 'die Pause', es: 'el descanso' },
  { de: 'der Urlaub', es: 'las vacaciones' },
  { de: 'der Vertrag', es: 'el contrato' },
  { de: 'der Arzt / die Ärztin', es: 'el médico' },
  { de: 'der Anwalt', es: 'el abogado' },
  { de: 'der Ingenieur', es: 'el ingeniero' },
  { de: 'der Lehrer', es: 'el profesor' },
  { de: 'der Koch', es: 'el cocinero' },
  { de: 'der Fahrer', es: 'el conductor' },
  { de: 'der Polizist', es: 'el policía' },
  { de: 'der Architekt', es: 'el arquitecto' },
  { de: 'der Programmierer', es: 'el programador' },
  { de: 'der Journalist', es: 'el periodista' },
  { de: 'der Verkäufer', es: 'el vendedor' },
  { de: 'der Kellner', es: 'el camarero' },
  { de: 'die Sekretärin', es: 'la secretaria' },

  // ── Reisen & Transport ───────────────────────────────────────────────────
  { de: 'die Reise', es: 'el viaje' },
  { de: 'das Gepäck', es: 'el equipaje' },
  { de: 'der Koffer', es: 'la maleta' },
  { de: 'der Pass', es: 'el pasaporte' },
  { de: 'das Visum', es: 'el visado' },
  { de: 'die Unterkunft', es: 'el alojamiento' },
  { de: 'die Reservierung', es: 'la reserva' },
  { de: 'das Ticket / die Fahrkarte', es: 'el billete' },
  { de: 'der Ausflug', es: 'la excursión' },
  { de: 'die Sehenswürdigkeit', es: 'el monumento' },
  { de: 'der Stadtplan', es: 'el plano de la ciudad' },
  { de: 'der Tourist', es: 'el turista' },
  { de: 'das Auto', es: 'el coche' },
  { de: 'der Bus', es: 'el autobús' },
  { de: 'die U-Bahn', es: 'el metro' },
  { de: 'das Taxi', es: 'el taxi' },
  { de: 'das Flugzeug', es: 'el avión' },
  { de: 'der Zug', es: 'el tren' },
  { de: 'das Schiff', es: 'el barco' },
  { de: 'das Fahrrad', es: 'la bicicleta' },

  // ── Gesundheit ───────────────────────────────────────────────────────────
  { de: 'die Gesundheit', es: 'la salud' },
  { de: 'der Patient', es: 'el paciente' },
  { de: 'das Medikament', es: 'el medicamento' },
  { de: 'die Tablette', es: 'la pastilla' },
  { de: 'die Krankheit', es: 'la enfermedad' },
  { de: 'der Schmerz', es: 'el dolor' },
  { de: 'das Fieber', es: 'la fiebre' },
  { de: 'der Husten', es: 'la tos' },
  { de: 'der Schnupfen', es: 'el resfriado' },
  { de: 'die Grippe', es: 'la gripe' },
  { de: 'die Allergie', es: 'la alergia' },
  { de: 'die Operation', es: 'la operación' },
  { de: 'die Untersuchung', es: 'la revisión médica' },
  { de: 'der Verband', es: 'el vendaje' },
  { de: 'die Verletzung', es: 'la herida' },
  { de: 'der Notfall', es: 'la emergencia' },
  { de: 'das Rezept', es: 'la receta' },
  { de: 'die Spritze', es: 'la inyección' },

  // ── Technologie ──────────────────────────────────────────────────────────
  { de: 'der Computer', es: 'el ordenador' },
  { de: 'das Handy', es: 'el móvil' },
  { de: 'das Internet', es: 'internet' },
  { de: 'die Webseite', es: 'la página web' },
  { de: 'die App', es: 'la aplicación' },
  { de: 'die E-Mail', es: 'el correo electrónico' },
  { de: 'der Drucker', es: 'la impresora' },
  { de: 'der Bildschirm', es: 'la pantalla' },
  { de: 'die Tastatur', es: 'el teclado' },
  { de: 'die Kamera', es: 'la cámara' },
  { de: 'das Foto', es: 'la foto' },
  { de: 'das Video', es: 'el vídeo' },
  { de: 'das Passwort', es: 'la contraseña' },
  { de: 'die Datei', es: 'el archivo' },
  { de: 'das Netzwerk', es: 'la red' },

  // ── Geld & Einkaufen ─────────────────────────────────────────────────────
  { de: 'das Geld', es: 'el dinero' },
  { de: 'der Preis', es: 'el precio' },
  { de: 'teuer', es: 'caro' },
  { de: 'günstig / billig', es: 'barato' },
  { de: 'die Rechnung', es: 'la factura' },
  { de: 'die Quittung', es: 'el recibo' },
  { de: 'die Kreditkarte', es: 'la tarjeta de crédito' },
  { de: 'das Bargeld', es: 'el dinero en efectivo' },
  { de: 'der Rabatt', es: 'el descuento' },
  { de: 'das Angebot', es: 'la oferta' },
  { de: 'die Kasse', es: 'la caja' },
  { de: 'das Kaufhaus', es: 'el gran almacén' },
  { de: 'die Steuer', es: 'el impuesto' },
  { de: 'das Budget', es: 'el presupuesto' },

  // ── Kleidung ─────────────────────────────────────────────────────────────
  { de: 'das Hemd', es: 'la camisa' },
  { de: 'die Hose', es: 'los pantalones' },
  { de: 'das Kleid', es: 'el vestido' },
  { de: 'der Rock', es: 'la falda' },
  { de: 'der Pullover', es: 'el jersey' },
  { de: 'die Jacke', es: 'la chaqueta' },
  { de: 'der Mantel', es: 'el abrigo' },
  { de: 'der Schuh', es: 'el zapato' },
  { de: 'der Stiefel', es: 'la bota' },
  { de: 'die Socke', es: 'el calcetín' },
  { de: 'die Unterwäsche', es: 'la ropa interior' },
  { de: 'der Hut', es: 'el sombrero' },
  { de: 'die Mütze', es: 'el gorro' },
  { de: 'der Schal', es: 'la bufanda' },
  { de: 'die Handschuhe', es: 'los guantes' },
  { de: 'der Gürtel', es: 'el cinturón' },
  { de: 'die Brille', es: 'las gafas' },

  // ── Tiere ────────────────────────────────────────────────────────────────
  { de: 'das Tier', es: 'el animal' },
  { de: 'der Hund', es: 'el perro' },
  { de: 'die Katze', es: 'el gato' },
  { de: 'das Pferd', es: 'el caballo' },
  { de: 'die Kuh', es: 'la vaca' },
  { de: 'das Schwein', es: 'el cerdo' },
  { de: 'das Schaf', es: 'la oveja' },
  { de: 'der Vogel', es: 'el pájaro' },
  { de: 'der Fisch', es: 'el pez' },
  { de: 'die Schlange', es: 'la serpiente' },
  { de: 'der Löwe', es: 'el león' },
  { de: 'der Tiger', es: 'el tigre' },
  { de: 'der Bär', es: 'el oso' },
  { de: 'der Wolf', es: 'el lobo' },
  { de: 'der Elefant', es: 'el elefante' },
  { de: 'der Affe', es: 'el mono' },
  { de: 'die Maus', es: 'el ratón' },
  { de: 'das Insekt', es: 'el insecto' },

  // ── Adjektive ────────────────────────────────────────────────────────────
  { de: 'groß', es: 'grande' },
  { de: 'klein', es: 'pequeño' },
  { de: 'lang', es: 'largo' },
  { de: 'kurz', es: 'corto' },
  { de: 'breit', es: 'ancho' },
  { de: 'schmal', es: 'estrecho' },
  { de: 'hoch', es: 'alto' },
  { de: 'niedrig / tief', es: 'bajo' },
  { de: 'schwer', es: 'pesado' },
  { de: 'leicht', es: 'ligero' },
  { de: 'schnell', es: 'rápido' },
  { de: 'langsam', es: 'lento' },
  { de: 'neu', es: 'nuevo' },
  { de: 'alt', es: 'viejo' },
  { de: 'jung', es: 'joven' },
  { de: 'modern', es: 'moderno' },
  { de: 'gut', es: 'bueno' },
  { de: 'schlecht', es: 'malo' },
  { de: 'schön', es: 'bonito' },
  { de: 'hässlich', es: 'feo' },
  { de: 'sauber', es: 'limpio' },
  { de: 'schmutzig', es: 'sucio' },
  { de: 'voll', es: 'lleno' },
  { de: 'leer', es: 'vacío' },
  { de: 'warm', es: 'cálido' },
  { de: 'kalt', es: 'frío' },
  { de: 'heiß', es: 'caliente' },
  { de: 'kühl', es: 'fresco' },
  { de: 'trocken', es: 'seco' },
  { de: 'nass', es: 'mojado' },
  { de: 'laut', es: 'ruidoso' },
  { de: 'leise', es: 'silencioso' },
  { de: 'hell', es: 'claro' },
  { de: 'dunkel', es: 'oscuro' },
  { de: 'stark', es: 'fuerte' },
  { de: 'schwach', es: 'débil' },
  { de: 'reich', es: 'rico' },
  { de: 'arm', es: 'pobre' },
  { de: 'glücklich', es: 'feliz' },
  { de: 'traurig', es: 'triste' },
  { de: 'müde', es: 'cansado' },
  { de: 'krank', es: 'enfermo' },
  { de: 'gesund', es: 'sano' },
  { de: 'interessant', es: 'interesante' },
  { de: 'langweilig', es: 'aburrido' },
  { de: 'wichtig', es: 'importante' },
  { de: 'nötig', es: 'necesario' },
  { de: 'möglich', es: 'posible' },
  { de: 'unmöglich', es: 'imposible' },
  { de: 'sicher', es: 'seguro' },
  { de: 'gefährlich', es: 'peligroso' },
  { de: 'einfach', es: 'sencillo' },
  { de: 'kompliziert', es: 'complicado' },
  { de: 'berühmt', es: 'famoso' },
  { de: 'allgemein', es: 'general' },
  { de: 'besonders', es: 'especial' },
  { de: 'normal', es: 'normal' },
  { de: 'anders / verschieden', es: 'diferente' },
  { de: 'ähnlich', es: 'similar' },
  { de: 'gleich', es: 'igual' },
  { de: 'typisch', es: 'típico' },

  // ── Emotionen & Charakter ────────────────────────────────────────────────
  { de: 'die Freude', es: 'la alegría' },
  { de: 'die Traurigkeit', es: 'la tristeza' },
  { de: 'die Angst', es: 'el miedo' },
  { de: 'die Wut', es: 'la rabia' },
  { de: 'die Überraschung', es: 'la sorpresa' },
  { de: 'die Liebe', es: 'el amor' },
  { de: 'der Hass', es: 'el odio' },
  { de: 'die Hoffnung', es: 'la esperanza' },
  { de: 'die Enttäuschung', es: 'la decepción' },
  { de: 'stolz', es: 'orgulloso' },
  { de: 'neidisch', es: 'envidioso' },
  { de: 'dankbar', es: 'agradecido' },
  { de: 'freundlich', es: 'amable' },
  { de: 'höflich', es: 'educado' },
  { de: 'unhöflich', es: 'maleducado' },
  { de: 'ehrlich', es: 'honesto' },
  { de: 'treu', es: 'fiel' },
  { de: 'mutig', es: 'valiente' },
  { de: 'schüchtern', es: 'tímido' },
  { de: 'neugierig', es: 'curioso' },
  { de: 'geduldig', es: 'paciente' },
  { de: 'ungeduldig', es: 'impaciente' },
  { de: 'selbstbewusst', es: 'seguro de sí mismo' },
  { de: 'großzügig', es: 'generoso' },
  { de: 'geizig', es: 'tacaño' },
  { de: 'verantwortungsbewusst', es: 'responsable' },
  { de: 'kreativ', es: 'creativo' },
  { de: 'intelligent', es: 'inteligente' },
  { de: 'lustig / komisch', es: 'gracioso' },
  { de: 'ernst', es: 'serio' },

  // ── Bildung ──────────────────────────────────────────────────────────────
  { de: 'das Buch', es: 'el libro' },
  { de: 'das Heft', es: 'el cuaderno' },
  { de: 'der Stift', es: 'el bolígrafo' },
  { de: 'das Papier', es: 'el papel' },
  { de: 'der Lehrer', es: 'el profesor' },
  { de: 'der Schüler', es: 'el alumno' },
  { de: 'die Prüfung', es: 'el examen' },
  { de: 'die Note', es: 'la nota' },
  { de: 'die Hausaufgabe', es: 'la tarea' },
  { de: 'die Klasse', es: 'la clase' },
  { de: 'das Fach', es: 'la asignatura' },
  { de: 'die Sprache', es: 'el idioma' },
  { de: 'das Wort', es: 'la palabra' },
  { de: 'der Satz', es: 'la frase' },
  { de: 'der Fehler', es: 'el error' },
  { de: 'das Zeugnis', es: 'el boletín de notas' },

  // ── Musik & Freizeit ─────────────────────────────────────────────────────
  { de: 'die Musik', es: 'la música' },
  { de: 'das Lied', es: 'la canción' },
  { de: 'das Konzert', es: 'el concierto' },
  { de: 'der Film', es: 'la película' },
  { de: 'das Buch', es: 'el libro' },
  { de: 'der Sport', es: 'el deporte' },
  { de: 'das Spiel', es: 'el juego' },
  { de: 'das Hobby', es: 'el hobby' },
  { de: 'die Freizeit', es: 'el tiempo libre' },
  { de: 'die Ferien', es: 'las vacaciones' },
  { de: 'das Fest', es: 'la fiesta' },
  { de: 'der Geburtstag', es: 'el cumpleaños' },
  { de: 'das Geschenk', es: 'el regalo' },
  { de: 'der Fußball', es: 'el fútbol' },
  { de: 'das Tennis', es: 'el tenis' },

  // ── Abstrakte Begriffe ───────────────────────────────────────────────────
  { de: 'die Idee', es: 'la idea' },
  { de: 'das Problem', es: 'el problema' },
  { de: 'die Lösung', es: 'la solución' },
  { de: 'der Grund / das Motiv', es: 'la razón' },
  { de: 'das Ergebnis', es: 'el resultado' },
  { de: 'die Möglichkeit', es: 'la posibilidad' },
  { de: 'der Unterschied', es: 'la diferencia' },
  { de: 'die Wahl', es: 'la elección' },
  { de: 'der Erfolg', es: 'el éxito' },
  { de: 'die Erfahrung', es: 'la experiencia' },
  { de: 'das Wissen', es: 'el conocimiento' },
  { de: 'die Meinung', es: 'la opinión' },
  { de: 'die Frage', es: 'la pregunta' },
  { de: 'die Antwort', es: 'la respuesta' },
  { de: 'die Hilfe', es: 'la ayuda' },
  { de: 'der Rat', es: 'el consejo' },
  { de: 'die Information', es: 'la información' },
  { de: 'die Nachricht', es: 'el mensaje' },
  { de: 'das Gespräch', es: 'la conversación' },
  { de: 'die Entscheidung', es: 'la decisión' },
  { de: 'die Veränderung', es: 'el cambio' },
  { de: 'der Plan', es: 'el plan' },
  { de: 'das Ziel', es: 'el objetivo' },
  { de: 'die Aufgabe', es: 'la tarea' },
  { de: 'die Verantwortung', es: 'la responsabilidad' },
  { de: 'die Freiheit', es: 'la libertad' },
  { de: 'die Wahrheit', es: 'la verdad' },
  { de: 'die Lüge', es: 'la mentira' },
  { de: 'das Vertrauen', es: 'la confianza' },
  { de: 'der Respekt', es: 'el respeto' },
  { de: 'die Gesellschaft', es: 'la sociedad' },
  { de: 'die Kultur', es: 'la cultura' },
  { de: 'die Geschichte', es: 'la historia' },
  { de: 'die Politik', es: 'la política' },
  { de: 'die Wirtschaft', es: 'la economía' },
  { de: 'die Umwelt', es: 'el medio ambiente' },
  { de: 'die Energie', es: 'la energía' },
  { de: 'das Recht', es: 'el derecho' },
  { de: 'die Pflicht', es: 'el deber' },
  { de: 'der Vorteil', es: 'la ventaja' },
  { de: 'der Nachteil', es: 'la desventaja' },
  { de: 'der Fortschritt', es: 'el progreso' },
  { de: 'die Entwicklung', es: 'el desarrollo' },
  { de: 'die Situation', es: 'la situación' },
  { de: 'das Thema', es: 'el tema' },
  { de: 'der Bereich', es: 'el campo / el área' },
  { de: 'das Beispiel', es: 'el ejemplo' },
  { de: 'der Teil', es: 'la parte' },
  { de: 'die Gruppe', es: 'el grupo' },
  { de: 'die Mehrheit', es: 'la mayoría' },
  { de: 'die Minderheit', es: 'la minoría' },

  // ── B1/B2 Verben (erweitert) ─────────────────────────────────────────────
  { de: 'sich vorstellen', es: 'imaginarse' },
  { de: 'sich vorstellen (präsentieren)', es: 'presentarse' },
  { de: 'ausgeben (Geld)', es: 'gastar' },
  { de: 'verdienen', es: 'ganar' },
  { de: 'sparen', es: 'ahorrar' },
  { de: 'leihen', es: 'prestar' },
  { de: 'borgen', es: 'pedir prestado' },
  { de: 'anbieten', es: 'ofrecer' },
  { de: 'akzeptieren', es: 'aceptar' },
  { de: 'ablehnen', es: 'rechazar' },
  { de: 'behaupten', es: 'afirmar' },
  { de: 'leugnen', es: 'negar' },
  { de: 'bestätigen', es: 'confirmar' },
  { de: 'übersetzen', es: 'traducir' },
  { de: 'erfinden', es: 'inventar' },
  { de: 'entdecken', es: 'descubrir' },
  { de: 'bemerken', es: 'notar' },
  { de: 'erkennen', es: 'reconocer' },
  { de: 'vermuten', es: 'suponer' },
  { de: 'beweisen', es: 'demostrar' },
  { de: 'vergleichen', es: 'comparar' },
  { de: 'unterscheiden', es: 'distinguir' },
  { de: 'kombinieren', es: 'combinar' },
  { de: 'verbinden', es: 'conectar' },
  { de: 'trennen', es: 'separar' },
  { de: 'organisieren', es: 'organizar' },
  { de: 'planen', es: 'planificar' },
  { de: 'vorbereiten', es: 'preparar' },
  { de: 'durchführen', es: 'realizar' },
  { de: 'abschließen / beenden', es: 'terminar' },
  { de: 'anfangen', es: 'comenzar' },
  { de: 'fortsetzen', es: 'continuar' },
  { de: 'aufhören', es: 'dejar de' },
  { de: 'wiederholen', es: 'repetir' },
  { de: 'üben', es: 'practicar' },
  { de: 'trainieren', es: 'entrenar' },
  { de: 'unterrichten', es: 'enseñar' },
  { de: 'studieren', es: 'estudiar' },
  { de: 'recherchieren', es: 'investigar' },
  { de: 'analysieren', es: 'analizar' },
  { de: 'lösen', es: 'resolver' },
  { de: 'reparieren', es: 'reparar' },
  { de: 'zerstören', es: 'destruir' },
  { de: 'erstellen / erschaffen', es: 'crear' },
  { de: 'entwickeln', es: 'desarrollar' },
  { de: 'wachsen', es: 'crecer' },
  { de: 'erhöhen / steigern', es: 'aumentar' },
  { de: 'verringern / senken', es: 'reducir' },
  { de: 'überprüfen', es: 'revisar' },
  { de: 'kontrollieren', es: 'controlar' },
  { de: 'führen / leiten', es: 'dirigir' },
  { de: 'regieren', es: 'gobernar' },
  { de: 'kämpfen', es: 'luchar' },
  { de: 'gewinnen (Streit)', es: 'vencer' },
  { de: 'feiern', es: 'celebrar' },
  { de: 'einladen', es: 'invitar' },
  { de: 'begrüßen', es: 'saludar' },
  { de: 'sich verabschieden', es: 'despedirse' },
  { de: 'gratulieren', es: 'felicitar' },
  { de: 'sich beschweren', es: 'quejarse' },
  { de: 'entschuldigen', es: 'disculparse' },
  { de: 'danken', es: 'agradecer' },
  { de: 'sich erinnern', es: 'acordarse' },
  { de: 'erzählen', es: 'contar' },
  { de: 'beschreiben', es: 'describir' },
  { de: 'berichten', es: 'informar' },
  { de: 'warnen', es: 'advertir' },
  { de: 'empfehlen', es: 'recomendar' },
  { de: 'vorschlagen', es: 'proponer' },
  { de: 'zustimmen', es: 'estar de acuerdo' },
  { de: 'widersprechen', es: 'contradecir' },
  { de: 'diskutieren', es: 'discutir' },
  { de: 'debattieren', es: 'debatir' },
  { de: 'überzeugen', es: 'convencer' },
  { de: 'beeinflussen', es: 'influir' },
  { de: 'auffordern', es: 'pedir' },
  { de: 'bitten', es: 'pedir' },
  { de: 'befehlen', es: 'ordenar' },
  { de: 'erlauben', es: 'dejar' },
  { de: 'verbieten', es: 'prohibir' },
  { de: 'hinzufügen', es: 'añadir' },
  { de: 'entfernen', es: 'eliminar' },
  { de: 'auswählen', es: 'elegir' },
  { de: 'bevorzugen', es: 'preferir' },
  { de: 'verzichten auf', es: 'renunciar a' },
  { de: 'sich weigern', es: 'negarse' },
  { de: 'riskieren', es: 'arriesgar' },
  { de: 'wagen', es: 'atreverse' },
  { de: 'hoffen', es: 'esperar' },
  { de: 'träumen', es: 'soñar' },
  { de: 'sich wünschen', es: 'desear' },
  { de: 'zweifeln', es: 'dudar' },
  { de: 'zögern', es: 'vacilar' },
  { de: 'sich beeilen', es: 'apresurarse' },
  { de: 'sich entspannen', es: 'relajarse' },
  { de: 'sich ärgern', es: 'enfadarse' },
  { de: 'sich freuen', es: 'alegrarse' },
  { de: 'sich schämen', es: 'avergonzarse' },
  { de: 'sich fürchten', es: 'tener miedo' },

  // ── Haus & Haushalt (erweitert) ──────────────────────────────────────────
  { de: 'der Keller', es: 'el sótano' },
  { de: 'der Dachboden', es: 'el desván' },
  { de: 'der Balkon', es: 'el balcón' },
  { de: 'die Terrasse', es: 'la terraza' },
  { de: 'der Garten', es: 'el jardín' },
  { de: 'die Garage', es: 'el garaje' },
  { de: 'der Aufzug', es: 'el ascensor' },
  { de: 'die Heizung', es: 'la calefacción' },
  { de: 'die Klimaanlage', es: 'el aire acondicionado' },
  { de: 'der Strom', es: 'la electricidad' },
  { de: 'das Gas', es: 'el gas' },
  { de: 'das Wasser (Versorgung)', es: 'el agua corriente' },
  { de: 'die Miete', es: 'el alquiler' },
  { de: 'der Vermieter', es: 'el casero' },
  { de: 'der Mieter', es: 'el inquilino' },
  { de: 'der Nachbar', es: 'el vecino' },
  { de: 'die Wand', es: 'la pared' },
  { de: 'die Decke (Zimmer)', es: 'el techo' },
  { de: 'der Boden', es: 'el suelo' },
  { de: 'das Dach', es: 'el tejado' },
  { de: 'die Klingel', es: 'el timbre' },
  { de: 'der Briefkasten', es: 'el buzón' },
  { de: 'das Waschbecken', es: 'el lavabo' },
  { de: 'die Dusche', es: 'la ducha' },
  { de: 'die Badewanne', es: 'la bañera' },
  { de: 'die Toilette', es: 'el váter' },
  { de: 'der Mikrowelle', es: 'el microondas' },
  { de: 'der Geschirrspüler', es: 'el lavavajillas' },
  { de: 'das Geschirr', es: 'la vajilla' },
  { de: 'der Topf', es: 'la olla' },
  { de: 'die Pfanne', es: 'la sartén' },
  { de: 'das Messer', es: 'el cuchillo' },
  { de: 'die Gabel', es: 'el tenedor' },
  { de: 'der Löffel', es: 'la cuchara' },
  { de: 'die Tasse', es: 'la taza' },
  { de: 'der Teller', es: 'el plato' },
  { de: 'das Glas', es: 'el vaso' },
  { de: 'die Flasche', es: 'la botella' },
  { de: 'die Serviette', es: 'la servilleta' },

  // ── Schule & Bildung (erweitert) ─────────────────────────────────────────
  { de: 'die Grundschule', es: 'la escuela primaria' },
  { de: 'das Gymnasium', es: 'el instituto' },
  { de: 'der Kindergarten', es: 'el jardín de infancia' },
  { de: 'die Klasse (Raum)', es: 'el aula' },
  { de: 'der Unterricht', es: 'la clase' },
  { de: 'die Pause', es: 'el recreo' },
  { de: 'der Stundenplan', es: 'el horario' },
  { de: 'die Mathematik', es: 'las matemáticas' },
  { de: 'die Wissenschaft', es: 'la ciencia' },
  { de: 'die Biologie', es: 'la biología' },
  { de: 'die Chemie', es: 'la química' },
  { de: 'die Physik', es: 'la física' },
  { de: 'die Geschichte', es: 'la historia' },
  { de: 'die Geografie', es: 'la geografía' },
  { de: 'die Kunst', es: 'el arte' },
  { de: 'die Musik (Fach)', es: 'la música' },
  { de: 'der Sport (Fach)', es: 'la educación física' },
  { de: 'die Philosophie', es: 'la filosofía' },
  { de: 'die Psychologie', es: 'la psicología' },
  { de: 'die Rechtswissenschaft', es: 'el derecho' },
  { de: 'die Medizin', es: 'la medicina' },
  { de: 'die Ingenieurwissenschaft', es: 'la ingeniería' },
  { de: 'das Stipendium', es: 'la beca' },
  { de: 'der Abschluss', es: 'el título' },
  { de: 'das Diplom', es: 'el diploma' },
  { de: 'die Dissertation', es: 'la tesis' },
  { de: 'der Professor', es: 'el catedrático' },
  { de: 'die Vorlesung', es: 'la conferencia' },
  { de: 'das Seminar', es: 'el seminario' },
  { de: 'die Hausarbeit', es: 'el trabajo de clase' },

  // ── Gesundheit (erweitert) ───────────────────────────────────────────────
  { de: 'die Apotheke', es: 'la farmacia' },
  { de: 'die Notaufnahme', es: 'urgencias' },
  { de: 'die Krankenkasse', es: 'el seguro médico' },
  { de: 'der Blutdruck', es: 'la tensión arterial' },
  { de: 'der Herzinfarkt', es: 'el infarto' },
  { de: 'der Schlaganfall', es: 'el ictus' },
  { de: 'der Diabetes', es: 'la diabetes' },
  { de: 'der Krebs', es: 'el cáncer' },
  { de: 'die Impfung', es: 'la vacuna' },
  { de: 'die Physiotherapie', es: 'la fisioterapia' },
  { de: 'die Psychotherapie', es: 'la psicoterapia' },
  { de: 'der Stress', es: 'el estrés' },
  { de: 'der Schlaf', es: 'el sueño' },
  { de: 'die Ernährung', es: 'la alimentación' },
  { de: 'die Diät', es: 'la dieta' },
  { de: 'die Übung / das Training', es: 'el ejercicio' },
  { de: 'das Gewicht', es: 'el peso' },
  { de: 'die Kalorien', es: 'las calorías' },
  { de: 'die Vitamin', es: 'la vitamina' },
  { de: 'das Symptom', es: 'el síntoma' },
  { de: 'die Diagnose', es: 'el diagnóstico' },
  { de: 'die Behandlung', es: 'el tratamiento' },
  { de: 'der Chirurg', es: 'el cirujano' },
  { de: 'die Krankenschwester', es: 'la enfermera' },
  { de: 'der Krankenpfleger', es: 'el enfermero' },
  { de: 'der Zahnarzt', es: 'el dentista' },
  { de: 'die Brille', es: 'las gafas' },
  { de: 'die Kontaktlinse', es: 'la lentilla' },
  { de: 'der Rollstuhl', es: 'la silla de ruedas' },
  { de: 'die Krücke', es: 'la muleta' },

  // ── Wirtschaft & Finanzen ────────────────────────────────────────────────
  { de: 'die Inflation', es: 'la inflación' },
  { de: 'die Rezession', es: 'la recesión' },
  { de: 'das Wachstum', es: 'el crecimiento' },
  { de: 'der Markt', es: 'el mercado' },
  { de: 'die Börse', es: 'la bolsa' },
  { de: 'die Aktie', es: 'la acción' },
  { de: 'die Investition', es: 'la inversión' },
  { de: 'der Gewinn', es: 'el beneficio' },
  { de: 'der Verlust', es: 'la pérdida' },
  { de: 'die Kosten', es: 'los costes' },
  { de: 'das Einkommen', es: 'los ingresos' },
  { de: 'die Ausgabe', es: 'el gasto' },
  { de: 'die Schulden', es: 'las deudas' },
  { de: 'der Kredit', es: 'el crédito' },
  { de: 'der Zinssatz', es: 'el tipo de interés' },
  { de: 'die Hypothek', es: 'la hipoteca' },
  { de: 'das Konto', es: 'la cuenta bancaria' },
  { de: 'die Überweisung', es: 'la transferencia' },
  { de: 'der Kontoauszug', es: 'el extracto bancario' },
  { de: 'die Währung', es: 'la moneda' },
  { de: 'der Wechselkurs', es: 'el tipo de cambio' },
  { de: 'die Mehrwertsteuer', es: 'el IVA' },
  { de: 'die Einkommensteuer', es: 'el impuesto sobre la renta' },
  { de: 'das Gehalt (monatlich)', es: 'el salario' },
  { de: 'die Rente', es: 'la pensión' },
  { de: 'die Sozialversicherung', es: 'la seguridad social' },
  { de: 'die Arbeitslosigkeit', es: 'el desempleo' },
  { de: 'der Streik', es: 'la huelga' },
  { de: 'die Gewerkschaft', es: 'el sindicato' },

  // ── Politik & Gesellschaft ───────────────────────────────────────────────
  { de: 'die Demokratie', es: 'la democracia' },
  { de: 'die Diktatur', es: 'la dictadura' },
  { de: 'die Regierung', es: 'el gobierno' },
  { de: 'das Parlament', es: 'el parlamento' },
  { de: 'die Partei', es: 'el partido' },
  { de: 'die Wahl', es: 'las elecciones' },
  { de: 'der Präsident', es: 'el presidente' },
  { de: 'der Minister', es: 'el ministro' },
  { de: 'das Gesetz', es: 'la ley' },
  { de: 'die Verfassung', es: 'la constitución' },
  { de: 'die Menschenrechte', es: 'los derechos humanos' },
  { de: 'die Gleichheit', es: 'la igualdad' },
  { de: 'die Diskriminierung', es: 'la discriminación' },
  { de: 'der Rassismus', es: 'el racismo' },
  { de: 'der Sexismus', es: 'el sexismo' },
  { de: 'die Immigration', es: 'la inmigración' },
  { de: 'der Flüchtling', es: 'el refugiado' },
  { de: 'der Krieg', es: 'la guerra' },
  { de: 'der Frieden', es: 'la paz' },
  { de: 'der Terrorismus', es: 'el terrorismo' },
  { de: 'die Kriminalität', es: 'la delincuencia' },
  { de: 'der Diebstahl', es: 'el robo' },
  { de: 'der Mord', es: 'el asesinato' },
  { de: 'das Gericht', es: 'el tribunal' },
  { de: 'der Richter', es: 'el juez' },
  { de: 'der Angeklagte', es: 'el acusado' },
  { de: 'das Urteil', es: 'la sentencia' },
  { de: 'die Strafe', es: 'el castigo' },
  { de: 'das Gefängnis', es: 'la prisión' },

  // ── Umwelt & Natur (erweitert) ───────────────────────────────────────────
  { de: 'der Klimawandel', es: 'el cambio climático' },
  { de: 'die Erderwärmung', es: 'el calentamiento global' },
  { de: 'die Umweltverschmutzung', es: 'la contaminación' },
  { de: 'das Recycling', es: 'el reciclaje' },
  { de: 'der Müll', es: 'la basura' },
  { de: 'die Ökologie', es: 'la ecología' },
  { de: 'nachhaltig', es: 'sostenible' },
  { de: 'erneuerbar', es: 'renovable' },
  { de: 'die Sonnenenergie', es: 'la energía solar' },
  { de: 'die Windenergie', es: 'la energía eólica' },
  { de: 'das Erdöl', es: 'el petróleo' },
  { de: 'die Kohle', es: 'el carbón' },
  { de: 'der Treibhauseffekt', es: 'el efecto invernadero' },
  { de: 'die Ozonschicht', es: 'la capa de ozono' },
  { de: 'das Ökosystem', es: 'el ecosistema' },
  { de: 'die Artenvielfalt', es: 'la biodiversidad' },
  { de: 'das Aussterben', es: 'la extinción' },
  { de: 'der Naturschutz', es: 'la conservación de la naturaleza' },
  { de: 'die Überschwemmung', es: 'la inundación' },
  { de: 'die Dürre', es: 'la sequía' },
  { de: 'das Erdbeben', es: 'el terremoto' },
  { de: 'der Vulkan', es: 'el volcán' },
  { de: 'der Tsunami', es: 'el tsunami' },
  { de: 'der Waldbrand', es: 'el incendio forestal' },
  { de: 'die Pflanze', es: 'la planta' },

  // ── Medien & Kommunikation ───────────────────────────────────────────────
  { de: 'die Zeitung', es: 'el periódico' },
  { de: 'die Zeitschrift', es: 'la revista' },
  { de: 'das Magazin', es: 'la revista' },
  { de: 'die Nachricht', es: 'la noticia' },
  { de: 'der Artikel', es: 'el artículo' },
  { de: 'die Schlagzeile', es: 'el titular' },
  { de: 'die Sendung', es: 'el programa' },
  { de: 'die Dokumentation', es: 'el documental' },
  { de: 'die Serie', es: 'la serie' },
  { de: 'der Podcast', es: 'el podcast' },
  { de: 'die soziale Medien', es: 'las redes sociales' },
  { de: 'der Hashtag', es: 'el hashtag' },
  { de: 'der Kommentar', es: 'el comentario' },
  { de: 'teilen (online)', es: 'compartir' },
  { de: 'folgen (online)', es: 'seguir' },
  { de: 'hochladen', es: 'subir' },
  { de: 'herunterladen', es: 'descargar' },
  { de: 'der Benutzer', es: 'el usuario' },
  { de: 'das Profil', es: 'el perfil' },
  { de: 'der Inhalt', es: 'el contenido' },
  { de: 'die Werbung', es: 'la publicidad' },
  { de: 'die Anzeige', es: 'el anuncio' },
  { de: 'das Abonnement', es: 'la suscripción' },
  { de: 'der Kanal', es: 'el canal' },
  { de: 'live senden', es: 'transmitir en directo' },

  // ── Wohnen & Stadtleben ──────────────────────────────────────────────────
  { de: 'das Viertel', es: 'el barrio' },
  { de: 'die Vorstadt', es: 'el suburbio' },
  { de: 'das Zentrum', es: 'el centro' },
  { de: 'die Ampel', es: 'el semáforo' },
  { de: 'der Kreisverkehr', es: 'la rotonda' },
  { de: 'der Bürgersteig', es: 'la acera' },
  { de: 'die Kreuzung', es: 'el cruce' },
  { de: 'die Einbahnstraße', es: 'la calle de sentido único' },
  { de: 'das Parkhaus', es: 'el aparcamiento' },
  { de: 'die Autobahn', es: 'la autopista' },
  { de: 'die Landstraße', es: 'la carretera' },
  { de: 'der Zebrastreifen', es: 'el paso de peatones' },
  { de: 'die Bushaltestelle', es: 'la parada de autobús' },
  { de: 'die Haltestelle', es: 'la parada' },
  { de: 'der Fahrplan', es: 'el horario' },
  { de: 'der Stau', es: 'el atasco' },
  { de: 'der Unfall', es: 'el accidente' },
  { de: 'die Umleitung', es: 'el desvío' },
  { de: 'der Führerschein', es: 'el carnet de conducir' },
  { de: 'das Kennzeichen', es: 'la matrícula' },

  // ── Sport & Freizeit (erweitert) ─────────────────────────────────────────
  { de: 'das Schwimmbad', es: 'la piscina' },
  { de: 'das Fitnessstudio', es: 'el gimnasio' },
  { de: 'der Sportplatz', es: 'el campo deportivo' },
  { de: 'das Stadion', es: 'el estadio' },
  { de: 'die Mannschaft', es: 'el equipo' },
  { de: 'der Spieler', es: 'el jugador' },
  { de: 'der Trainer', es: 'el entrenador' },
  { de: 'das Training', es: 'el entrenamiento' },
  { de: 'das Spiel (Partie)', es: 'el partido' },
  { de: 'das Turnier', es: 'el torneo' },
  { de: 'der Meister', es: 'el campeón' },
  { de: 'der Pokal', es: 'el trofeo' },
  { de: 'die Medaille', es: 'la medalla' },
  { de: 'der Marathon', es: 'el maratón' },
  { de: 'das Yoga', es: 'el yoga' },
  { de: 'das Boxen', es: 'el boxeo' },
  { de: 'das Schwimmen', es: 'la natación' },
  { de: 'der Ski', es: 'el esquí' },
  { de: 'die Wanderung', es: 'la excursión a pie' },
  { de: 'klettern', es: 'escalar' },
  { de: 'segeln', es: 'navegar' },
  { de: 'surfen', es: 'surfear' },

  // ── Essen & Restaurant (erweitert) ──────────────────────────────────────
  { de: 'die Speisekarte', es: 'la carta' },
  { de: 'die Vorspeise', es: 'el primer plato' },
  { de: 'der Hauptgang', es: 'el plato principal' },
  { de: 'der Nachtisch', es: 'el postre' },
  { de: 'der Kellner', es: 'el camarero' },
  { de: 'die Reservierung', es: 'la reserva' },
  { de: 'das Trinkgeld', es: 'la propina' },
  { de: 'der Imbiss', es: 'el bocadillo' },
  { de: 'das Fast Food', es: 'la comida rápida' },
  { de: 'vegetarisch', es: 'vegetariano' },
  { de: 'vegan', es: 'vegano' },
  { de: 'glutenfrei', es: 'sin gluten' },
  { de: 'laktosefrei', es: 'sin lactosa' },
  { de: 'biologisch', es: 'ecológico' },
  { de: 'frisch', es: 'fresco' },
  { de: 'gefroren', es: 'congelado' },
  { de: 'gekocht', es: 'cocido' },
  { de: 'gebraten', es: 'frito' },
  { de: 'gegrillt', es: 'a la plancha' },
  { de: 'roh', es: 'crudo' },
  { de: 'süß', es: 'dulce' },
  { de: 'salzig', es: 'salado' },
  { de: 'sauer', es: 'ácido' },
  { de: 'scharf (Gewürz)', es: 'picante' },
  { de: 'bitter', es: 'amargo' },

  // ── Redewendungen & Ausdrücke ────────────────────────────────────────────
  { de: 'Es tut mir leid.', es: 'Lo siento.' },
  { de: 'Entschuldigung.', es: 'Perdona.' },
  { de: 'Wie bitte?', es: '¿Cómo?' },
  { de: 'Ich verstehe nicht.', es: 'No entiendo.' },
  { de: 'Könnten Sie das wiederholen?', es: '¿Puede repetir?' },
  { de: 'Was bedeutet das?', es: '¿Qué significa eso?' },
  { de: 'Wie heißt das auf Spanisch?', es: '¿Cómo se dice en español?' },
  { de: 'Ich bin einverstanden.', es: 'Estoy de acuerdo.' },
  { de: 'Ich bin nicht einverstanden.', es: 'No estoy de acuerdo.' },
  { de: 'Meiner Meinung nach...', es: 'En mi opinión...' },
  { de: 'Ich bin sicher, dass...', es: 'Estoy seguro de que...' },
  { de: 'Ich glaube, dass...', es: 'Creo que...' },
  { de: 'Es ist möglich, dass...', es: 'Es posible que...' },
  { de: 'Zum Glück...', es: 'Por suerte...' },
  { de: 'Leider...', es: 'Desgraciadamente...' },
  { de: 'Eigentlich...', es: 'En realidad...' },
  { de: 'Natürlich.', es: 'Por supuesto.' },
  { de: 'Auf keinen Fall.', es: 'De ninguna manera.' },
  { de: 'So ein Pech!', es: '¡Qué mala suerte!' },
  { de: 'Wie schade!', es: '¡Qué lástima!' },
  { de: 'Das ist fantastisch!', es: '¡Qué maravilla!' },

  // ── Zahlen (Ordinalzahlen) ───────────────────────────────────────────────
  { de: 'erste/r/s', es: 'primero' },
  { de: 'zweite/r/s', es: 'segundo' },
  { de: 'dritte/r/s', es: 'tercero' },
  { de: 'vierte/r/s', es: 'cuarto' },
  { de: 'fünfte/r/s', es: 'quinto' },
  { de: 'sechste/r/s', es: 'sexto' },
  { de: 'siebte/r/s', es: 'séptimo' },
  { de: 'achte/r/s', es: 'octavo' },
  { de: 'neunte/r/s', es: 'noveno' },
  { de: 'zehnte/r/s', es: 'décimo' },
  { de: 'letzte/r/s', es: 'último' },

  // ── Präpositionen & Konnektoren ──────────────────────────────────────────
  { de: 'wegen', es: 'debido a' },
  { de: 'trotzdem', es: 'sin embargo' },
  { de: 'außerdem', es: 'además' },
  { de: 'deshalb', es: 'por eso' },
  { de: 'obwohl', es: 'aunque' },
  { de: 'damit (Zweck)', es: 'para que' },
  { de: 'während', es: 'mientras' },
  { de: 'bevor', es: 'antes de que' },
  { de: 'nachdem', es: 'después de que' },
  { de: 'sobald', es: 'en cuanto' },
  { de: 'falls', es: 'en caso de que' },
  { de: 'sowohl ... als auch', es: 'tanto ... como' },
  { de: 'entweder ... oder', es: 'o ... o' },
  { de: 'weder ... noch', es: 'ni ... ni' },
  { de: 'je ... desto', es: 'cuanto más ... más' },
  { de: 'statt', es: 'en lugar de' },
  { de: 'ohne dass', es: 'sin que' },
  { de: 'damit (folge)', es: 'de modo que' },
  { de: 'indem', es: 'haciendo' },
  { de: 'sofern', es: 'siempre que' },
  { de: 'gegenüber', es: 'frente a' },
  { de: 'innerhalb', es: 'dentro de' },
  { de: 'außerhalb', es: 'fuera de' },
  { de: 'entlang', es: 'a lo largo de' },
  { de: 'anstatt', es: 'en vez de' },

  // ── Beschreibung & Mengen ────────────────────────────────────────────────
  { de: 'viel', es: 'mucho' },
  { de: 'wenig', es: 'poco' },
  { de: 'genug', es: 'suficiente' },
  { de: 'zu viel', es: 'demasiado' },
  { de: 'fast', es: 'casi' },
  { de: 'ungefähr', es: 'aproximadamente' },
  { de: 'mindestens', es: 'al menos' },
  { de: 'höchstens', es: 'como máximo' },
  { de: 'genauso wie', es: 'igual que' },
  { de: 'mehr als', es: 'más que' },
  { de: 'weniger als', es: 'menos que' },
  { de: 'so viel wie', es: 'tanto como' },
  { de: 'ziemlich', es: 'bastante' },
  { de: 'sehr', es: 'muy' },
  { de: 'ein bisschen', es: 'un poco' },
  { de: 'kaum', es: 'apenas' },
  { de: 'insgesamt', es: 'en total' },
  { de: 'gemeinsam', es: 'juntos' },
  { de: 'alleine', es: 'solo' },
  { de: 'gegenseitig', es: 'mutuamente' },

  // ── Eigenschaftswörter B2 ────────────────────────────────────────────────
  { de: 'aufgeregt', es: 'emocionado' },
  { de: 'entspannt', es: 'relajado' },
  { de: 'gestresst', es: 'estresado' },
  { de: 'überrascht', es: 'sorprendido' },
  { de: 'begeistert', es: 'entusiasmado' },
  { de: 'enttäuscht', es: 'decepcionado' },
  { de: 'verletzt', es: 'herido' },
  { de: 'zufrieden', es: 'satisfecho' },
  { de: 'unzufrieden', es: 'insatisfecho' },
  { de: 'motiviert', es: 'motivado' },
  { de: 'demotiviert', es: 'desmotivado' },
  { de: 'konzentriert', es: 'concentrado' },
  { de: 'abgelenkt', es: 'distraído' },
  { de: 'erschöpft', es: 'agotado' },
  { de: 'ausgeruht', es: 'descansado' },
  { de: 'nervös', es: 'nervioso' },
  { de: 'ruhig', es: 'tranquilo' },
  { de: 'ängstlich', es: 'ansioso' },
  { de: 'optimistisch', es: 'optimista' },
  { de: 'pessimistisch', es: 'pesimista' },
  { de: 'realistisch', es: 'realista' },
  { de: 'idealistisch', es: 'idealista' },
  { de: 'praktisch', es: 'práctico' },
  { de: 'theoretisch', es: 'teórico' },
  { de: 'formal', es: 'formal' },
  { de: 'informell', es: 'informal' },
  { de: 'öffentlich', es: 'público' },
  { de: 'privat', es: 'privado' },
  { de: 'kostenlos', es: 'gratuito' },
  { de: 'kostenpflichtig', es: 'de pago' },
  { de: 'verfügbar', es: 'disponible' },
  { de: 'besetzt', es: 'ocupado' },
  { de: 'frei', es: 'libre' },
  { de: 'notwendig', es: 'imprescindible' },
  { de: 'überflüssig', es: 'innecesario' },
  { de: 'effizient', es: 'eficiente' },
  { de: 'ineffizient', es: 'ineficiente' },
  { de: 'zuverlässig', es: 'fiable' },
  { de: 'unzuverlässig', es: 'poco fiable' },
  { de: 'flexibel', es: 'flexible' },
  { de: 'starr', es: 'rígido' },

  // ── Körper & Gesundheit (erweitert) ─────────────────────────────────────
  { de: 'der Ellbogen', es: 'el codo' },
  { de: 'das Handgelenk', es: 'la muñeca' },
  { de: 'der Daumen', es: 'el pulgar' },
  { de: 'der Zeigefinger', es: 'el índice' },
  { de: 'der Ringfinger', es: 'el anular' },
  { de: 'der kleine Finger', es: 'el meñique' },
  { de: 'der Nagel', es: 'la uña' },
  { de: 'der Knöchel', es: 'el tobillo' },
  { de: 'die Wade', es: 'la pantorrilla' },
  { de: 'der Oberschenkel', es: 'el muslo' },
  { de: 'die Hüfte', es: 'la cadera' },
  { de: 'der Bauch (Organ)', es: 'el abdomen' },
  { de: 'die Leber', es: 'el hígado' },
  { de: 'die Niere', es: 'el riñón' },
  { de: 'der Magen', es: 'el estómago' },
  { de: 'der Darm', es: 'el intestino' },
  { de: 'das Fett', es: 'la grasa' },
  { de: 'der Muskel', es: 'el músculo' },
  { de: 'der Knochen', es: 'el hueso' },
  { de: 'das Gelenk', es: 'la articulación' },

  // ── Reisen & Kultur (erweitert) ──────────────────────────────────────────
  { de: 'das Denkmal', es: 'el monumento' },
  { de: 'die Burg', es: 'el castillo' },
  { de: 'der Palast', es: 'el palacio' },
  { de: 'der Dom', es: 'la catedral' },
  { de: 'die Moschee', es: 'la mezquita' },
  { de: 'der Tempel', es: 'el templo' },
  { de: 'die Synagoge', es: 'la sinagoga' },
  { de: 'die Ausstellung', es: 'la exposición' },
  { de: 'das Gemälde', es: 'el cuadro' },
  { de: 'die Skulptur', es: 'la escultura' },
  { de: 'die Architektur', es: 'la arquitectura' },
  { de: 'das Kunstwerk', es: 'la obra de arte' },
  { de: 'der Künstler', es: 'el artista' },
  { de: 'das Festival', es: 'el festival' },
  { de: 'die Tradition', es: 'la tradición' },
  { de: 'der Brauch', es: 'la costumbre' },
  { de: 'die Folklore', es: 'el folclore' },
  { de: 'die Gastronomie', es: 'la gastronomía' },
  { de: 'die Landesküche', es: 'la cocina local' },
  { de: 'das Souvenir', es: 'el recuerdo' },
  { de: 'das Doppelzimmer', es: 'la habitación doble' },
  { de: 'das Einzelzimmer', es: 'la habitación individual' },
  { de: 'die Jugendherberge', es: 'el albergue juvenil' },
  { de: 'die Pension', es: 'la pensión' },
  { de: 'der Campingplatz', es: 'el camping' },

  // ── Wissenschaft & Technik ───────────────────────────────────────────────
  { de: 'das Experiment', es: 'el experimento' },
  { de: 'die Theorie', es: 'la teoría' },
  { de: 'das Labor', es: 'el laboratorio' },
  { de: 'die Forschung', es: 'la investigación' },
  { de: 'der Forscher', es: 'el investigador' },
  { de: 'die Entdeckung', es: 'el descubrimiento' },
  { de: 'die Erfindung', es: 'el invento' },
  { de: 'der Algorithmus', es: 'el algoritmo' },
  { de: 'die Daten', es: 'los datos' },
  { de: 'die künstliche Intelligenz', es: 'la inteligencia artificial' },
  { de: 'der Roboter', es: 'el robot' },
  { de: 'die Software', es: 'el software' },
  { de: 'die Hardware', es: 'el hardware' },
  { de: 'die Datenbank', es: 'la base de datos' },
  { de: 'der Code', es: 'el código' },
  { de: 'die Cybersicherheit', es: 'la ciberseguridad' },
  { de: 'die Cloud', es: 'la nube' },
  { de: 'das Update', es: 'la actualización' },
  { de: 'der Download', es: 'la descarga' },
  { de: 'der Upload', es: 'la subida' },
  { de: 'das Backup', es: 'la copia de seguridad' },
  { de: 'die Schnittstelle', es: 'la interfaz' },

  // ── Abstrakta (erweitert) ─────────────────────────────────────────────────
  { de: 'der Anlass', es: 'la ocasión' },
  { de: 'der Ausdruck', es: 'la expresión' },
  { de: 'die Wirkung', es: 'el efecto' },
  { de: 'die Ursache', es: 'la causa' },
  { de: 'die Folge', es: 'la consecuencia' },
  { de: 'das Risiko', es: 'el riesgo' },
  { de: 'die Chance', es: 'la oportunidad' },
  { de: 'die Herausforderung', es: 'el desafío' },
  { de: 'das Hindernis', es: 'el obstáculo' },
  { de: 'der Kompromiss', es: 'el compromiso' },
  { de: 'der Konflikt', es: 'el conflicto' },
  { de: 'die Lösung', es: 'la solución' },
  { de: 'der Fortschritt', es: 'el avance' },
  { de: 'der Rückschritt', es: 'el retroceso' },
  { de: 'der Wandel', es: 'el cambio' },
  { de: 'die Stabilität', es: 'la estabilidad' },
  { de: 'die Unsicherheit', es: 'la incertidumbre' },
  { de: 'die Transparenz', es: 'la transparencia' },
  { de: 'die Effizienz', es: 'la eficiencia' },
  { de: 'die Qualität', es: 'la calidad' },
  { de: 'die Quantität', es: 'la cantidad' },
  { de: 'der Standard', es: 'el nivel' },
  { de: 'die Norm', es: 'la norma' },
  { de: 'die Ausnahme', es: 'la excepción' },
  { de: 'die Regel', es: 'la regla' },
  { de: 'die Methode', es: 'el método' },
  { de: 'der Prozess', es: 'el proceso' },
  { de: 'das System', es: 'el sistema' },
  { de: 'das Modell', es: 'el modelo' },
  { de: 'die Struktur', es: 'la estructura' },
  { de: 'die Funktion', es: 'la función' },
  { de: 'der Zweck', es: 'el propósito' },
  { de: 'die Bedeutung', es: 'el significado' },
  { de: 'der Kontext', es: 'el contexto' },
  { de: 'der Aspekt', es: 'el aspecto' },
  { de: 'die Perspektive', es: 'la perspectiva' },
  { de: 'der Standpunkt', es: 'el punto de vista' },
  { de: 'der Einfluss', es: 'la influencia' },
  { de: 'die Beziehung', es: 'la relación' },
  { de: 'die Verbindung', es: 'la conexión' },
  { de: 'die Zusammenarbeit', es: 'la colaboración' },
  { de: 'die Kommunikation', es: 'la comunicación' },
];
